### PR TITLE
Updates to sync_repo_and_patch to support reproducible builds

### PR DESCRIPTION
**Pull request by p3ck**
For the CI workflow it is important to be able to reproduce builds.
This patch will do two things.  if a repos variable is defined with
repo/path/on/disk;SHA entries it will check out that specific
version instead master.  Second, if master is checked out this
will record the current HEAD commit.

Our CI workflow will cat the recorded_repos entry to config_$user.sh
which we then archive as an artifact.

This should allow us to re-run builds and get the same git repos.

### CODE REVIEW

**Comment by russellb** [comment]
Can you please update the commit message with a more thorough explanation of the problem being solved, and how this patch addresses it?

**Comment by p3ck** [comment]
yes - sorry about that.

**Comment by p3ck** [comment]
@russellb I updated the commit and also the initial description here.  If you have any thoughts on reproducible builds I would be happy to listen.  It could be that we should simply archive all of these as artifacts in our build process.

**Comment by russellb** [comment]
> For the CI workflow it is important to be able to reproduce builds.

I'm not sure why this is important, exactly.  I'd expect CI to be chasing the latest commits?

Stated a bit differently, is the problem statement: "For a given CI run, we need to know exactly which versions of all components were used" ?

**Comment by p3ck** [comment]
@russellb CI will be testing the latest and the latest working combination will be passed onto QE and eventually released.  This matches the updated problem statement.

**Comment by russellb** [comment]
> @russellb CI will be testing the latest and the latest working combination will be passed onto QE and eventually released. This matches the updated problem statement.

OK - there's no intention of using this repo in any sort of release pipeline.  We should discuss offline ...

**Pull request closed without merging**
