### PR TITLE
Pull localy built images from local for masters

### PR DESCRIPTION
**Pull request by derekhiggins**
Add the ability for masters to pull localy built images
for development and ci jobs.

### CODE REVIEW

**Comment by metal3ci** [comment]
Build FAILURE, see build http://10.8.144.11:8080/job/dev-tools/991/

**Comment by metal3ci** [comment]
Build SUCCESS, see build http://10.8.144.11:8080/job/dev-tools/1007/

**Comment by metal3ci** [comment]
Build FAILURE, see build http://10.8.144.11:8080/job/dev-tools/1023/

**Comment by metal3ci** [comment]
Build SUCCESS, see build http://10.8.144.11:8080/job/dev-tools/1029/

**Comment by derekhiggins** [comment]
Closing, out of date,

**Pull request closed without merging**
