### PR TITLE
Update LOCAL_IMAGES to work with local mirrored registry

### PR DESCRIPTION
**Pull request by derekhiggins**
We no longer need to build a custom installer and a couple of
small fixups.

### CODE REVIEW

**Comment by metal3ci** [comment]
Build FAILURE, see build http://10.8.144.11:8080/job/dev-tools/1396/

**Comment by metal3ci** [comment]
Build FAILURE, see build http://10.8.144.11:8080/job/dev-tools/1397/

**Comment by hardys** [comment]
The CI failure seems real:

```
Dec 24 09:57:22 |  Trying to pull quay.io/metal3-io/ironic:master...
Dec 24 09:57:22 |    unexpected end of JSON input
Dec 24 09:57:22 |  Error: error pulling image "quay.io/metal3-io/ironic:master": unable to pull quay.io/metal3-io/ironic:master: unable to pull image: Error initializing source docker://quay.io/metal3-io/ironic:master: error getting username and password: error reading JSON file "combined-pullsecret--7KNtqWtcif": error unmarshaling JSON at "combined-pullsecret--7KNtqWtcif": unexpected end of JSON input
Dec 24 09:57:22 |  make: *** [ironic] Error 125
```

**Comment by hardys** [comment]
I tested this locally and it seemed to work OK, but the CI failure does seem real, will try to reproduce it

**Comment by metal3ci** [comment]
Build FAILURE, see build http://10.8.144.11:8080/job/dev-tools/1398/

**Comment by derekhiggins** [comment]
> I tested this locally and it seemed to work OK, but the CI failure does seem real, will try to reproduce it

see update to 02_... , I think the problem is that $REGISTRY_CREDS is only create if we are mirroring images.

**Comment by metal3ci** [comment]
Build FAILURE, see build http://10.8.144.11:8080/job/dev-tools/1399/

**Comment by metal3ci** [comment]
Build SUCCESS, see build http://10.8.144.11:8080/job/dev-tools/1400/

**Pull request merged**
