### PR TITLE
OCPBUGS-19676: Allow agent VSphere installs by simulating VMWare host

### PR DESCRIPTION
**Pull request by bfournie**
When the platform type is "vsphere", set the host's manufacturer to VMWare in order to pass the assisted-service validations and allow the installation to proceed.

### CODE REVIEW

**Review by rwsu — COMMENTED** [review]
/lgtm

**Review by rwsu — COMMENTED** [review]
/lgtm

**Review by pawanpinjarkar — COMMENTED** [review]
/lgtm

**Review by rwsu — APPROVED** [review]

**Pull request merged**
