### PR TITLE
Document METAL3_DEV_ENV variable

### PR DESCRIPTION
**Pull request by elfosardo**

### CODE REVIEW

**Comment by elfosardo** [comment]
the issue with e2e-metal-ipi-serial-ipv4 is independent from this change

**Comment by elfosardo** [comment]
/retest
giving it another chance

**Comment by derekhiggins** [comment]
/hold
I already run install requirements multiple times, when I've made local changes to metal3-dev-env, I want to get this error message, it reminds me to set METAL3_DEV_ENV  (to avoid running sync_repo_and_patch)

If the error message doesn't happen my local updates would be silently zapped, without realising it I wouldn't be running the code I wanted and my changes would be lost.

**Comment by elfosardo** [comment]
@derekhiggins @dtantsur please give it another look, thanks!

**Comment by derekhiggins** [comment]
/unhold
/lgtm
thanks

**Pull request merged**
