### PR TITLE
Fix RHCOS location and update to no-early-exit installer

### PR DESCRIPTION
**Pull request by markmc**
RHCOS image locations have changed

Bring in openshift-metalkube/kni-installer#136

### CODE REVIEW

**Comment by metal3ci** [comment]
Build FAILURE, see build http://10.8.144.11:8080/job/dev-tools/839/

**Comment by russellb** [comment]
> Build FAILURE, see build http://10.8.144.11:8080/job/dev-tools/839/

I think this was the CI run that started without the extra RHCOS fix

**Comment by metal3ci** [comment]
Build FAILURE, see build http://10.8.144.11:8080/job/dev-tools/840/

**Comment by markmc** [comment]
> Build FAILURE, see build http://10.8.144.11:8080/job/dev-tools/840/

```
Jul 06 14:02:45 |  level=debug msg="Still waiting for the cluster to initialize: Working towards 4.2.0-0.ci-2019-07-03-145946-kni.2: 100% complete, waiting on authentication"
Jul 06 14:04:26 |  level=fatal msg="failed to initialize the cluster: Working towards 4.2.0-0.ci-2019-07-03-145946-kni.2: 100% complete, waiting on authentication"
```

I've seen this locally too, and eventually it does complete ...

**Comment by russellb** [comment]
> > Build FAILURE, see build http://10.8.144.11:8080/job/dev-tools/840/
> 
> ```
> Jul 06 14:02:45 |  level=debug msg="Still waiting for the cluster to initialize: Working towards 4.2.0-0.ci-2019-07-03-145946-kni.2: 100% complete, waiting on authentication"
> Jul 06 14:04:26 |  level=fatal msg="failed to initialize the cluster: Working towards 4.2.0-0.ci-2019-07-03-145946-kni.2: 100% complete, waiting on authentication"
> ```
> 
> I've seen this locally too, and eventually it does complete ...

OK, I think we should just merge this.

It would be nice to debug why this takes so long.  We should look at how OpenShift CI collects logs from a cluster.  In this case I'd like to see the authentication operator log, but we don't have it.

**Pull request merged**
