### PR TITLE
Adding flaper87 to the OWNERS file

### PR DESCRIPTION
**Pull request by flaper87**
Signed-off-by: Flavio Percoco <flavio@redhat.com>

### CODE REVIEW

**Comment by flaper87** [comment]
> * lranjbar

@hardys could you please add Lisa as well?

**Comment by flaper87** [comment]
I switched the PR to just add myself to the OWNERS list. I was not aware of the `OWNERS` process in dev-script :)

**Comment by hardys** [comment]
Sounds good, we can add @flaper87 now and others in his team working on `assisted_deployment.sh` in future when needed.

We don't actually have a formal OWNERS process for this repo atm, but in general folks will first get added to the openshift-metal3 org, so CI jobs run automatically, then gain familiarity doing regular reviews/commits (and CI debugging since these scripts are used in IPI/AI CI jobs), then get added as an approver.

**Comment by stbenjam** [comment]
Would you mind putting yourself before hardys to keep the alphabetical sort?

**Comment by flaper87** [comment]
> Would you mind putting yourself before hardys to keep the alphabetical sort?

Done! Although, in my heart, @hardys will always be first! :bow:

**Pull request merged**
