### PR TITLE
use consumerRef instead of machineRef when registering hosts

### PR DESCRIPTION
**Pull request by dhellmann**

### CODE REVIEW

**Comment by dhellmann** [comment]
This should not be merged until https://github.com/openshift/cluster-api-provider-baremetal/pull/34 has landed and a new image is available.

**Comment by russellb** [comment]
@dhellmann dev-scripts still deploys an upstream BMO image though, so I don't think you have to block on the openshift PR?

**Comment by hardys** [comment]
> @dhellmann dev-scripts still deploys an upstream BMO image though, so I don't think you have to block on the openshift PR?

Yeah that's right, the 08 script is still deploying the upstream BMO with a sedded namespace so lets see what CI says :)

**Comment by metal3ci** [comment]
Build FAILURE, see build http://10.8.144.11:8080/job/dev-tools/825/

**Comment by metal3ci** [comment]
Build FAILURE, see build http://10.8.144.11:8080/job/dev-tools/833/

**Comment by hardys** [comment]
@dhellmann I think CI is failing because your fork of dev-scripts doesn't have the same name as the main repo:

```
+ git clone https://github.com/openshift-metal3/metal3-dev-scripts
Cloning into 'metal3-dev-scripts'...
fatal: could not read Username for 'https://github.com': No such device or address
```

I'm not sure if there's some way we can teach CI to figure out the for relationship, perhaps you could just rename your fork in the meantime?

**Comment by hardys** [comment]
cc @derekhiggins I think this is happening prior to run-ci.sh, can we perhaps look at the PR repo instead of the fork origin?

**Comment by dhellmann** [comment]
I have renamed my repo, for now. How do I re-run the test job?

**Comment by dhellmann** [comment]
Replaced with https://github.com/openshift-metal3/dev-scripts/pull/653

**Pull request closed without merging**
