### PR TITLE
Remove some cert approval related hacks.

### PR DESCRIPTION
**Pull request by russellb**
This patch cleans up some hacks that are no longer needed.  CSRs for
masters are automatically approved by a service runningon the
bootstrap node during the bootstrap process.

Workers is where we are still missing some pieces.  Move the fix-certs
cron job to the register_hosts script, which is where worker
deployment is kicked off.

Also remove the add-machine-ips and link-machine-and-node scripts.
cluster-api-provider-baremetal should now be automatically populating
the addresses field of Machines based on introspection data it gets
out of the BareMetalHost object for workers.  Removing these scripts
ensures we only rely on that code, and not a dev-script hack.

### CODE REVIEW

**Comment by metal3ci** [comment]
Build FAILURE, see build http://10.8.144.11:8080/job/dev-tools/922/

**Comment by stbenjam** [comment]
Workers are failing to come up:

```
Error from server (BadRequest): container "baremetal-operator" in pod "metal3-baremetal-operator-74fdb86688-wq8v9" is waiting to start: PodInitializing
```

Do we need some logic to check if bmo pods are up first?

**Comment by russellb** [comment]
> Workers are failing to come up:
> 
> ```
> Error from server (BadRequest): container "baremetal-operator" in pod "metal3-baremetal-operator-74fdb86688-wq8v9" is waiting to start: PodInitializing
> ```
> 
> Do we need some logic to check if bmo pods are up first?

The register_hosts script used to wait for a worker to come up, but I removed it since I didn't see anything that required waiting.  It makes sense for CI purposes, though.  I'll add something to `run_ci.sh`

**Comment by metal3ci** [comment]
Build SUCCESS, see build http://10.8.144.11:8080/job/dev-tools/925/

**Comment by russellb** [comment]
CI passes now. :-)

**Pull request merged**
