### PR TITLE
Only pin metal3-dev-env when not using a local checkout

### PR DESCRIPTION
**Pull request by hardys**
When someone sets METAL3_DEV_ENV it most likely means they want
to test a local checkout so lets not reset in this case.

Also move the pin to 23eab39fe9977994aeac7ab6af603beb52059b32
which is the latest at the time of testing this PR and works
locally for me since #1017 merged.

### CODE REVIEW

**Comment by stbenjam** [comment]
Looks fine to me, let's just see what CI says

**Comment by metal3ci** [comment]
Build FAILURE, see build http://10.8.144.11:8080/job/dev-tools/1736/

**Comment by russellb** [comment]
> Build FAILURE, see build http://10.8.144.11:8080/job/dev-tools/1736/

CI failed pretty early, during requirements installation.  maybe it's a legit failure?

**Comment by hardys** [comment]
> > Build FAILURE, see build http://10.8.144.11:8080/job/dev-tools/1736/
> 
> CI failed pretty early, during requirements installation. maybe it's a legit failure?

The error seems to be a 500 connecting to the github API (and there were github issues around the time the job ran IIRC), I'll re-run as I don't think it's related to the PR

**Comment by metal3ci** [comment]
Build SUCCESS, see build http://10.8.144.11:8080/job/dev-tools/1741/

**Pull request merged**
