### PR TITLE
Add timestamps to dev-scripts logs

### PR DESCRIPTION
**Pull request by stbenjam**

### CODE REVIEW

**Comment by stbenjam** [comment]
Not sure how much awking every line is going to add to the load, but something is taking a long time in CI -- more than an hour to get to running the installer and I want to see why.

**Comment by zaneb** [comment]
> Not sure how much awking every line is going to add to the load

awk is surprisingly fast in my experience.

**Comment by dhellmann** [comment]
@stbenjam Is it safe to remove the WIP from this PR?

**Comment by stbenjam** [comment]
Oh yea, should be good to go. The CI logs look like it's doing the right thing.

/retitle Add timestamps to dev-scripts logs

**Pull request merged**
