### PR TITLE
Update default RELEASE_STREAM to 4.15

### PR DESCRIPTION
**Pull request by cybertron**

### CODE REVIEW

**Comment by cybertron** [comment]
`Working towards 4.16.0-0.ci.test-2024-03-04-111539-ci-op-fv1ivy9m-latest`

Interesting. Does the agent job ignore this default release version?

/retest-required

**Comment by andfasano** [comment]
Overriding compact as https://github.com/openshift/ovn-kubernetes/pull/2089 did not merge yet

/override ci/prow/e2e-agent-compact-ipv4

**Pull request merged**
