### PR TITLE
Add support for additional networks

### PR DESCRIPTION
**Pull request by hardys**
This allows additional networks to be defined e.g

```
export EXTRA_NETWORK_NAMES="nmstate1 nmstate2"
export NMSTATE1_NETWORK_SUBNET_V4='192.168.221.0/24'
export NMSTATE1_NETWORK_SUBNET_V6='fd2e:6f44:5dd8:ca56::/120'
export NMSTATE2_NETWORK_SUBNET_V4='192.168.222.0/24'
export NMSTATE2_NETWORK_SUBNET_V6='fd2e:6f44:5dd8:cc56::/120'
```

Requires ansible role changes added via

https://github.com/metal3-io/metal3-dev-env/pull/852

### CODE REVIEW

**Comment by hardys** [comment]
WIP until https://github.com/metal3-io/metal3-dev-env/pull/852 lands

This can be tested locally via e.g `export METAL3_DEV_ENV="/home/shardy/metal3-dev-env"` where the local checkout has that PR applied

Testing locally this works for me, e.g:

```
export EXTRA_NETWORK_NAMES="nmstate1 nmstate2"
export NMSTATE1_NETWORK_SUBNET_V4='192.168.221.0/24'
export NMSTATE1_NETWORK_SUBNET_V6='fd2e:6f44:5dd8:ca56::/120'
export NMSTATE2_NETWORK_SUBNET_V4='192.168.222.0/24'
export NMSTATE2_NETWORK_SUBNET_V6='fd2e:6f44:5dd8:cc56::/120'
```

results in 

```
[shardy@master-1 dev-scripts]$ sudo virsh net-list --all
 Name       State      Autostart   Persistent
-----------------------------------------------
 default    active     yes         yes
 nmstate1   active     yes         yes
 nmstate2   active     yes         yes
 ostestbm   active     yes         yes
 ostestpr   inactive   yes         yes
```

```

**Comment by hardys** [comment]
/cc @cybertron @creydr 

Alternative to #1286

**Comment by creydr** [comment]
I deployed a cluster with this PR and https://github.com/metal3-io/metal3-dev-env/pull/852. The e2e test for https://github.com/openshift/kubernetes-nmstate passed. 

We could wait with this PR until https://github.com/metal3-io/metal3-dev-env/pull/852 got merged an then adjust https://github.com/openshift-metal3/dev-scripts/blob/918da5cba37ec38b47e67dbe08d53297e8dcb7ea/01_install_requirements.sh#L22 in this PR as well

**Comment by hardys** [comment]
Thanks for the feedback @creydr - I removed WIP from https://github.com/metal3-io/metal3-dev-env/pull/852/ and asked for reviews - feel free to comment there if you have time :)

**Comment by hardys** [comment]
https://github.com/metal3-io/metal3-dev-env/pull/852 merged so I updated the pin and this should be ready to land I think - ANSIBLE_VERSION also updated to align with metal3-dev-env

**Comment by hardys** [comment]
/test e2e-metal-ipi-ovn-ipv6

Hopefully https://github.com/openshift/origin/pull/26655 will fix the failure

**Comment by hardys** [comment]
@cybertron @creydr - I think this is ready for review if you're happy to proceed with this instead of #1286

**Comment by creydr** [comment]
I tested it in https://github.com/openshift-metal3/dev-scripts/pull/1312#issuecomment-977762604 with runnning the k-nmstate e2e tests and tonight again with the latest changes.
```
[core@master-0 ~]$ ip link
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: enp1s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP mode DEFAULT group default qlen 1000
    link/ether 00:16:ae:bb:05:00 brd ff:ff:ff:ff:ff:ff
3: enp2s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP mode DEFAULT group default qlen 1000
    link/ether 00:16:ae:bb:05:02 brd ff:ff:ff:ff:ff:ff
4: enp3s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP mode DEFAULT group default qlen 1000
    link/ether 00:16:ae:bb:05:04 brd ff:ff:ff:ff:ff:ff
5: enp4s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP mode DEFAULT group default qlen 1000
    link/ether 00:16:ae:bb:05:06 brd ff:ff:ff:ff:ff:ff
```

/lgtm

**Comment by yboaron** [comment]
I run multi nic dev-scripts deployment with this PR - looks OK

/lgtm

**Pull request merged**
