### PR TITLE
Cache the download of the oc client in CI

### PR DESCRIPTION
**Pull request by derekhiggins**
Download times for this file seem to vary a lot.

### CODE REVIEW

**Comment by hardys** [comment]
Yeah this was my motiviation for https://github.com/openshift-metal3/dev-scripts/pull/962 - the tarball is only like 20MB but sometimes my local test runs stalled for around a minute downloading.

**Comment by metal3ci** [comment]
Build FAILURE, see build http://10.8.144.11:8080/job/dev-tools/1580/

**Comment by metal3ci** [comment]
Build FAILURE, see build http://10.8.144.11:8080/job/dev-tools/1618/

**Comment by metal3ci** [comment]
Build FAILURE, see build http://10.8.144.11:8080/job/dev-tools/1632/

**Comment by metal3ci** [comment]
Build SUCCESS, see build http://10.8.144.11:8080/job/dev-tools/1637/

**Pull request merged**
