### PR TITLE
Cleanups/fixes to ansible roles

### LINKED ISSUE #378: make clean doesn't remove the vbmc configurations and daemons
After running "make clean" vbmcd is still running and vm configuration files are still in place

*# vbmc list*
+--------------------+---------+---------+------+
| Domain name        | Status  | Address | Port |
+--------------------+---------+---------+------+
| openshift_master_0 | running | ::      | 6230 |
| openshift_master_1 | running | ::      | 6231 |
| openshift_master_2 | running | ::      | 6232 |
| openshift_worker_0 | running | ::      | 6233 |
| openshift_worker_1 | running | ::      | 6234 |
| openshift_worker_2 | running | ::      | 6235 |
+--------------------+---------+---------+------+

*# ps aux|grep vbmc*
root      6477  0.1  0.0 486140 26124 ?        Ssl  Apr11  12:39 /usr/bin/python2 /usr/bin/vbmcd --foreground
root      6844  0.1  0.0 538748 35224 ?        Sl   Apr11  10:55 /usr/bin/python2 /usr/bin/vbmcd --foreground
root      6890  0.1  0.0 538892 35884 ?        Sl   Apr11  11:00 /usr/bin/python2 /usr/bin/vbmcd --foreground
root      6933  0.1  0.0 538892 36228 ?        Sl   Apr11  10:59 /usr/bin/python2 /usr/bin/vbmcd --foreground
root      6979  0.0  0.0 485752  5924 ?        Sl   Apr11   7:40 /usr/bin/python2 /usr/bin/vbmcd --foreground
root      7023  0.0  0.0 485752  5916 ?        Sl   Apr11   7:44 /usr/bin/python2 /usr/bin/vbmcd --foreground
root      7066  0.0  0.0 485752  5936 ?        Sl   Apr11   7:39 /usr/bin/python2 /usr/bin/vbmcd --foreground

*# ls -l /root/.vbmc/*
total 4
-rw-------. 1 root root  4 Apr 11 10:48 master.pid
drwxr-xr-x. 2 root root 20 Apr 11 10:48 openshift_master_0
drwxr-xr-x. 2 root root 20 Apr 11 10:48 openshift_master_1
drwxr-xr-x. 2 root root 20 Apr 11 10:48 openshift_master_2
drwxr-xr-x. 2 root root 20 Apr 11 10:48 openshift_worker_0
drwxr-xr-x. 2 root root 20 Apr 11 10:48 openshift_worker_1
drwxr-xr-x. 2 root root 20 Apr 11 10:48 openshift_worker_2

### PR DESCRIPTION
**Pull request by hardys**
These were derived from tripleo-quickstart and there are some variables/tasks/complexity which we don't need, so this is a first-pass at cleaning them up, removing unused things, and sanitising some naming.

Also I added a commit with teardown tasks for virtualbmc which should fix #378

### CODE REVIEW

**Comment by hardys** [comment]
@russellb we discussed this yesterday, this is a first-pass, there's still more to do but thought I'd push this as a first iteration for review/testing

**Comment by derekhiggins** [comment]
Build FAILURE, see build http://10.8.144.11:8080/job/dev-tools/613/

**Comment by hardys** [comment]
CI failure looks real, looking into it

**Comment by hardys** [comment]
Hmm strange, the `roles/libvirt/defaults/main.yml` isn't found via the `roles/libvirt/setup/meta/main.yml` dependency, but this works fine for me locally, I'll try adding a role include explicitly but I'm not clear why this is working locally but not in CI.. @derekhiggins any ideas?

**Comment by russellb** [comment]
My local failure was:

```
TASK [libvirt/setup : create the volume pool xml file] ***************************************************************************************************************************************
task path: /home/rbryant/dev-scripts/tripleo-quickstart-config/roles/libvirt/setup/tasks/main.yml:21
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: rbryant
<localhost> EXEC /bin/sh -c 'echo ~rbryant && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/rbryant/.ansible/tmp/ansible-tmp-1556805524.86-243656929161520 `" && echo ansible-tmp-1556805524.86-243656929161520="` echo /home/rbryant/.ansible/tmp/ansible-tmp-1556805524.86-243656929161520 `" ) && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /home/rbryant/.ansible/tmp/ansible-tmp-1556805524.86-243656929161520/ > /dev/null 2>&1 && sleep 0'
fatal: [localhost]: FAILED! => {
    "changed": false, 
    "msg": "AnsibleUndefinedVariable: 'libvirt_volume_pool' is undefined"
}
```

**Comment by hardys** [comment]
Thanks @russellb - for some reason I'm not seeing that so perhaps I have some untracked files locally, I'll mark this WIP and re-test.

Probably the best fix is to further flatten the roles and remove the weird nested meta-include completely - we could just pass a variable e.g state=teardown or something in the teardown case and select a task-include based on that in roles/libvirt/tasks/main.yml

**Comment by hardys** [comment]
Ah my bad, I forgot to add a file, re-testing then will update

**Comment by derekhiggins** [comment]
Build FAILURE, see build http://10.8.144.11:8080/job/dev-tools/614/

**Comment by hardys** [comment]
Hmm Ok so this got further but there was an error controlling the nodes via IPMI so maybe something is wrong with the virtbmc changes, investigating

```
Stderr: u'Get Auth Capabilities error\nError issuing Get Channel Authentication Capabilities request\nError: Unable to establish IPMI v2 / RMCP+ session\n'.: ProcessExecutionError: Unexpected error while running command.
2019-05-02 15:42:44.607 62 ERROR ironic.conductor.manager [req-2902e849-719c-4121-967b-10e3fe96e944 - - - - -] Failed to get power state for node 88795aa7-7373-4502-b4a2-fe5bba9da9ca. Error: IPMI call failed: power status.: IPMIFailure: IPMI call failed: power status.
```

**Comment by derekhiggins** [comment]
Build SUCCESS, see build http://10.8.144.11:8080/job/dev-tools/615/

**Comment by russellb** [comment]
@hardys not sure if it's the same thing, but I had a very similar error earlier, but not with this PR.  In my case I had to remove old config from `/root/.vbmc/`.

**Comment by russellb** [comment]
https://github.com/openshift-metal3/dev-scripts/pull/507 fixed my problem, at least

**Pull request merged**
