### PR TITLE
Migrate network config to NetworkManager keyfiles

### PR DESCRIPTION
**Pull request by elfosardo**
this takes back work done in https://github.com/openshift-metal3/dev-scripts/pull/1290 but using keyfiles instead of direct nmcli commands

### CODE REVIEW

**Comment by elfosardo** [comment]
interesting, this works perfectly locally

**Comment by elfosardo** [comment]
this has been tested on CentOS Stream 8 and 9 successfully
we're using Rocky 8.5 in CI which makes me think that's why it's failing here

**Comment by cybertron** [comment]
That's weird. This is working for me locally in Alma 8.6. :-/

**Comment by elfosardo** [comment]
> That's weird. This is working for me locally in Alma 8.6. :-/

@cybertron in CI we pin Rocky 8.5 and it doesn't like this :/

**Comment by cybertron** [comment]
Could we just unpin now that we have https://github.com/openshift-metal3/dev-scripts/commit/522d3c853a36c44125ea165cf8e633c5e88d7693 and don't need to pin in order for ipv6 to work? At least I think that's why we were pinned to 8.5.

**Comment by elfosardo** [comment]
/retest
may need to change a couple of things, let's rerun failed jobs to confirm

**Comment by elfosardo** [comment]
this is really unsettling:
+(./02_configure_host.sh:286): main(): sudo nmcli con show
NAME             UUID                                  TYPE      DEVICE     
cluster6bm       c4e94d83-6a93-499e-bf6a-628529b2466c  bridge    cluster6bm 
cluster6pr       3b2093a6-0149-3a8b-9ef6-4a775a94cb4c  bridge    cluster6pr 
virbr0           eaff8f5b-c6e0-4c96-a768-36d5f43310ff  bridge    virbr0     
cluster6bm-eth2  2150b483-d02f-40e2-ad74-c64d81bbe8ee  ethernet  eth2       
eth3             59cc9865-b3bd-33ef-86c5-0478d8bbc11f  ethernet  eth3    

but the error is:
"level=fatal msg=failed to fetch Terraform Variables: failed to fetch dependency of "Terraform Variables": failed to generate asset "Platform Provisioning Check": platform.baremetal.provisioningBridge: Invalid value: "cluster6pr": could not find interface "cluster6pr", valid interfaces are cluster6bm, lo"

**Comment by iurygregory** [comment]
@elfosardo just wondering if we still need this , should we trigger a retest in the jobs?

**Comment by elfosardo** [comment]
> @elfosardo just wondering if we still need this , should we trigger a retest in the jobs?

we definitely need this
please do not trigger a retest, it will still fail
troubleshooting the issue is taking some time

**Pull request closed without merging**
