### PR TITLE
Change default to be 2 workers

### PR DESCRIPTION
**Pull request by stbenjam**
Some of the instability and flakes in CI is believed to be caused by
only have 1 worker. Trying 2 workers as the default, but we might
have to bump up the packet instance to make this work.

If we can increase the packet instance and try out 2 workers for a week,
we should be able to see if this improves stability.

### CODE REVIEW

**Comment by cybertron** [comment]
I see my old dev environment with 1 worker is currently using 56 GB. Is this going to break developers on 64 GB boxes?

**Comment by stbenjam** [comment]
> I see my old dev environment with 1 worker is currently using 56 GB. Is this going to break developers on 64 GB boxes?

Yea, it's less than ideal. I don't know what to do about it, CI has a 79% fail rate over the last 7 days. Some of that was legit failures we fixed, some was CI/GitHub outages, but a lot of that is flakes that I'm being told are possibly because of the 3/1 setup.

**Comment by stbenjam** [comment]
Some stats for just periodic-ci-openshift-release-master-ocp-4.5-e2e-metal-ipi - of 53 runs, 77% failed, 20% of failures match "failed to renew lease openshift-kube-scheduler/kube-scheduler"

**Comment by hardys** [comment]
> I see my old dev environment with 1 worker is currently using 56 GB. Is this going to break developers on 64 GB boxes?

In my env with 3 masters and two workers deployed I see 68G usage, some of that is marked shared though so I'm not certain if it would push a 64G box into swap.

One option might be to tune the VM memory allocation as I see the worker is using 2 (of 8)GB and the master 5 (of 16) - however we've run into OOM issues previously with lower defaults so the current values aligned with what's tested e.g on AWS and other platforms, so we could trade one type of instability for another.

**Comment by stbenjam** [comment]
> In my env with 3 masters and 2 workers deployed I see 68G usage, some of that is marked shared though so I'm not certain if it would push a 64G box into swap.

It does look like e2e-metal-ipi completed with the cluster installed, but things fell apart shortly after. 

I think we're going to need to bump the packet instance up to the next tier.

**Comment by stbenjam** [comment]
https://github.com/openshift/release/pull/8716 bumps us to c3.medium.

**Comment by russellb** [comment]
> [openshift/release#8716](https://github.com/openshift/release/pull/8716) bumps us to c3.medium.

though that's still 64 GB RAM, right?  just a newer rev of hardware, newer CPU model?

**Comment by stbenjam** [comment]
> > [openshift/release#8716](https://github.com/openshift/release/pull/8716) bumps us to c3.medium.
> 
> though that's still 64 GB RAM, right? just a newer rev of hardware, newer CPU model?

Yea sorry, I looked at the table of instances wrong. However, it still passes, I bumped CI last Friday: https://github.com/openshift/release/pull/8716, and it was green 100% all weekend.

Today isn't great though... there's some red jobs I haven't dug into yet, but looks like it all fits in 64GB.

**Comment by russellb** [comment]
> > > [openshift/release#8716](https://github.com/openshift/release/pull/8716) bumps us to c3.medium.
> > 
> > 
> > though that's still 64 GB RAM, right? just a newer rev of hardware, newer CPU model?
> 
> Yea sorry, I looked at the table of instances wrong. However, it still passes, I bumped CI last Friday: [openshift/release#8716](https://github.com/openshift/release/pull/8716), and it was green 100% all weekend.
> 
> Today isn't great though... there's some red jobs I haven't dug into yet, but looks like it all fits in 64GB.

Sounds good.  Let's roll with this instance type for now.  I like the idea of sticking with their latest gen hardware.

**Comment by russellb** [comment]
/approve
/lgtm

@stbenjam want to un-hold this?

**Comment by stbenjam** [comment]
/override ci/prow/e2e-metal-ipi

Quay had some outage, it couldn't pull any images. We've seen this pass a bunch already since it's the default in CI anyway.

**Pull request merged**
