### PR TITLE
agent: Update README about AGENT_E2E_TEST_SCENARIO variable

### PR DESCRIPTION
**Pull request by SaravanaStorageNetwork**
Signed-off-by: Saravanakumar Arumugam <sarumuga@redhat.com>

### CODE REVIEW

**Comment by SaravanaStorageNetwork** [comment]
Fixes #1454

**Comment by SaravanaStorageNetwork** [comment]
@pawanpinjarkar  @celebdor  PTAL

**Review by pawanpinjarkar — APPROVED** [review]

**Pull request merged**
