### PR TITLE
agent: using api vip, ingress vip, cluster name and base domain for generating the agent manifests

### PR DESCRIPTION
**Pull request by andfasano**
Also, refactored the existing code to share the api/ingress vip build logic

### CODE REVIEW

**Review by pawanpinjarkar — APPROVED** [review]
/lgtm

**Review by elfosardo — COMMENTED** [review]
/lgtm

**Comment by lranjbar** [comment]
I want to eventually get some of these CRDs into reusable templates. For this PR I like putting this in a function though :)

/lgtm

**Review by lranjbar — APPROVED** [review]

**Comment by andfasano** [comment]
ipv6 job is failing for reasons not related to the current patch, it looks like @hardys pushed a patch for it https://github.com/openshift/cluster-etcd-operator/pull/785

**Comment by andfasano** [comment]
overriding ipv6 job, since the fix will be addressed by https://bugzilla.redhat.com/show_bug.cgi?id=2074544

/override e2e-metal-ipi-ovn-ipv6

**Pull request merged**
