### PR TITLE
Use KNI 4.1.0 rc.5 for release image

### PR DESCRIPTION
**Pull request by stbenjam**

### CODE REVIEW

**Comment by derekhiggins** [comment]
Build SUCCESS, see build http://10.8.144.11:8080/job/dev-tools/646/

**Comment by russellb** [comment]
@stbenjam we talked on slack about you rebuilding this image, lgtm after you update it

**Comment by derekhiggins** [comment]
Build SUCCESS, see build http://10.8.144.11:8080/job/dev-tools/647/

**Comment by stbenjam** [comment]
Updated, and CI is passing

**Pull request merged**
