### PR TITLE
WIP: Static ip

### PR DESCRIPTION
**Pull request by derekhiggins**
Cluster eventually comes up and completes

Continuing the work started here 
https://github.com/openshift-metal3/dev-scripts/pull/1297

TODO:
- bootstrap consistently times out when using static IPs, cluster eventually comes up after the installer has died
- ~~need to make dhcp config configurable~~
- test ipv6

### CODE REVIEW

**Comment by hardys** [comment]
> need to make dhcp config configurable

FYI I started looking at that via https://github.com/metal3-io/metal3-dev-env/pull/902 (now merged) - with that we can do something like this:

```
diff --git a/vm_setup_vars.yml b/vm_setup_vars.yml
index a345ce5..f3b60ed 100644
--- a/vm_setup_vars.yml
+++ b/vm_setup_vars.yml
@@ -61,13 +61,8 @@ external_network:
     netmask_v4: "{{ baremetal_network_cidr_v4|ipaddr('netmask') }}"
     address_v6: "{{ baremetal_network_cidr_v6|nthhost(1)|default('', true) }}"
     prefix_v6: "{{ baremetal_network_cidr_v6|ipaddr('prefix') }}"
-    dhcp_enabled: "{{ virsh_dhcp_enabled|bool }}"
-    dhcp_range_v4:
-      - "{{ baremetal_network_cidr_v4|nthhost(20) }}"
-      - "{{ baremetal_network_cidr_v4|nthhost(60) }}"
-    dhcp_range_v6:
-      - "{{ baremetal_network_cidr_v6|nthhost(20) }}"
-      - "{{ baremetal_network_cidr_v6|nthhost(60) }}"
+    dhcp_range_v4: "{{ [ baremetal_network_cidr_v4|nthhost(20), baremetal_network_cidr_v4|nthhost(60) ] if lookup('env', 'STATIC_IPS') == '' else [] }}"
+    dhcp_range_v6: "{{ [ baremetal_network_cidr_v6|nthhost(20), baremetal_network_cidr_v6|nthhost(60) ] if lookup('env', 'STATIC_IPS') == '' else [] }}"
     lease_expiry: "{{ lookup('env', 'DHCP_LEASE_EXPIRY') }}"
     nat_port_range:
       - 1024

```

**Comment by cybertron** [comment]
Having a shortcut to use static ips is useful, but I'm more interested in an interface to provide arbitrary network configs for the nodes so we can test things like bridge and bond configs. This is fairly important so we can duplicate (as close as possible, anyway) qe and customer network configurations.

Since networkConfigs are all multi-line, I don't think we want to try to pass them as env vars. I think we need an env var that points to a file or files containing the relevant networkConfigs. My first thought is to have the env var point to a directory (like ASSETS_EXTRA_FOLDER) and inside that there would be specific files - master-0.yaml, master-1.yaml, etc. containing the networkConfig for the respective node, as well as a vm_setup_extrahosts.yml for defining necessary DNS records.

None of this eliminates the need for a static ip shortcut option, but I'm wondering if it makes more sense to implement the arbitrary interface and then do the static ip config using that instead of as a one-off like it is now.

**Comment by cybertron** [comment]
I tried this locally and for some reason my workers are stuck on the agent image. I see a few errors in the logs, but it mostly looks like optional stuff and the agent run seems to complete so I'm not sure what's going on there. It's not specific to this patch because when I manually configured static IPs it did the exact same thing.

**Comment by cybertron** [comment]
To wrap up my previous comment, I believe there was an actual bug with networkConfig causing the failure. That's fixed now.

I pushed https://github.com/openshift-metal3/dev-scripts/pull/1418 as an example of what I was thinking for a generic networkConfig interface. It still needs something to add DNS records for static IPs, but with a little vm_setup_vars hacking it worked well. There should be some way to get the dns_extrahosts from the same directory.

**Comment by derekhiggins** [comment]
Closing as this was handled in https://github.com/openshift-metal3/dev-scripts/pull/1418

**Pull request closed without merging**
