### PR TITLE
Allow local gateway mode to be configured with OVN

### PR DESCRIPTION
**Pull request by jluhrsen**
Signed-off-by: Jamo Luhrsen <jluhrsen@gmail.com>

### CODE REVIEW

**Comment by jluhrsen** [comment]
@stbenjam , could you please review this? The PR as is has no effect on how the presubmit jobs are deployed. they will
take the default shared gateway mode. here is a [ovnkube-master log](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift-metal3_dev-scripts/1238/pull-ci-openshift-metal3-dev-scripts-master-e2e-metal-ipi-ovn-ipv6/1392324999708151808/artifacts/e2e-metal-ipi-ovn-ipv6/gather-extra/artifacts/pods/openshift-ovn-kubernetes_ovnkube-master-7dmcf_ovnkube-master.log) and [worker ovnkube-node log](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift-metal3_dev-scripts/1238/pull-ci-openshift-metal3-dev-scripts-master-e2e-metal-ipi-ovn-ipv6/1392324999708151808/artifacts/e2e-metal-ipi-ovn-ipv6/gather-extra/artifacts/pods/openshift-ovn-kubernetes_ovnkube-node-6x4qh_ovnkube-node.log) showing "shared" being
used. I also updated this PR (since removed) to put `export OVN_LOCAL_GATEWAY_MODE=local" in common.sh to
simulate that variable being available at install and you can see "local" being used in this [ovnkube-master log](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift-metal3_dev-scripts/1238/pull-ci-openshift-metal3-dev-scripts-master-e2e-metal-ipi-ovn-ipv6/1392526716634664960/artifacts/e2e-metal-ipi-ovn-ipv6/gather-extra/artifacts/pods/openshift-ovn-kubernetes_ovnkube-master-ffxgc_ovnkube-master.log) and [worker log](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift-metal3_dev-scripts/1238/pull-ci-openshift-metal3-dev-scripts-master-e2e-metal-ipi-ovn-ipv6/1392526716634664960/artifacts/e2e-metal-ipi-ovn-ipv6/gather-extra/artifacts/pods/openshift-ovn-kubernetes_ovnkube-node-2t2zx_ovnkube-node.log)
from this PRs presubmits.

**Comment by jluhrsen** [comment]
here's the [matching PR](https://github.com/openshift/release/pull/18539) in release/ that would create a job to take advantage of this one.

**Comment by stbenjam** [comment]
Thanks!!

**Pull request merged**
