### PR TITLE
WIP: assets: Drop ingress-controller manifest.

### PR DESCRIPTION
**Pull request by russellb**
The intention of this manifest was to change the node selector so that
the ingress controller would run on masters.

### CODE REVIEW

**Comment by russellb** [comment]
Marked as WIP while CI runs ...

**Comment by metal3ci** [comment]
Build FAILURE, see build http://10.8.144.11:8080/job/dev-tools/951/

**Comment by metal3ci** [comment]
Build FAILURE, see build http://10.8.144.11:8080/job/dev-tools/954/

**Comment by russellb** [comment]
The CI failure is real here.  This change is still needed, so more work is needed to figure out the right change to make to be able to drop this manifest.

**Comment by russellb** [comment]
tracked via #705

**Pull request closed without merging**
