### PR TITLE
MetalLB: Set default BGP type to FRR and Update FRR image

### PR DESCRIPTION
**Pull request by sabinaaledort**
Updating the FRR image to the d/s image built in CI.

### CODE REVIEW

**Comment by sabinaaledort** [comment]
/test e2e-metal-ipi
origin-tests failed (unrelated to my change)

**Comment by sabinaaledort** [comment]
/test e2e-metal-ipi
origin-tests failed (unrelated to my change)

**Comment by russellb** [comment]
/approve
/lgtm

remove the hold when you're ready for it to merge

**Pull request merged**
