### PR TITLE
Fix typo in the oc command after cluster is ready

### PR DESCRIPTION
**Pull request by elfosardo**
The correct flag is --kubeconfig

Also add single line instruction to message to set the KUBECONFIG
environment variable.

### CODE REVIEW

**Comment by elfosardo** [comment]
/retest
packet failures plus a weird timeout

**Comment by cybertron** [comment]
Ah, I think @dougsland ran into this too. Given that this is not making any functional changes I don't think ci matters.

/lgtm

**Comment by dougsland** [comment]
> Ah, I think @dougsland ran into this too. Given that this is not making any functional changes I don't think ci matters.
> 
> /lgtm

That's correct.

**Comment by elfosardo** [comment]
can anyone please override the 2 failing CI jobs? this change does not impact any moving part
thanks!

**Comment by hardys** [comment]
/override ci/prow/e2e-metal-ipi-proxy-ipv6
/override ci/prow/e2e-metal-ipi-proxy-ipv4

It seems these [recently added](https://github.com/openshift/release/pull/25912) tests aren't yet passing reliably, @andfasano is investigating and we'll skip them in the meantime

**Pull request merged**
