### PR TITLE
Demonstrate installer early exit is not necessary.

### PR DESCRIPTION
**Pull request by russellb**
The only remaining change we have running after exiting early from the
install process is adding IPs to the master Machines.  This is to
enable auto approval of CSRs.  We also have a cron job that does this,
so it's not necessary to do this in the middle of the install.  The
change moves it to post-install.

Related issues:
https://github.com/openshift-metal3/kni-installer/issues/60
https://github.com/openshift-metal3/dev-scripts/issues/260
https://github.com/metal3-io/baremetal-operator/issues/242

### CODE REVIEW

**Comment by russellb** [comment]
This worked locally for me, at least

**Comment by hardys** [comment]
To pick up https://github.com/openshift-metal3/kni-installer/pull/136 in the CI run, you'll have to hack ocp_install_env.sh to apply the patch and set export KNI_INSTALL_FROM_GIT=true I think?

**Comment by metal3ci** [comment]
Build FAILURE, see build http://10.8.144.11:8080/job/dev-tools/834/

**Comment by russellb** [comment]
> Build FAILURE, see build http://10.8.144.11:8080/job/dev-tools/834/

Failed due to a broken change in baremetal-operator, deployment actually succeeded and failed at the late register hosts step

**Comment by russellb** [comment]
> To pick up [openshift-metal3/kni-installer#136](https://github.com/openshift-metal3/kni-installer/pull/136) in the CI run, you'll have to hack ocp_install_env.sh to apply the patch and set export KNI_INSTALL_FROM_GIT=true I think?

Yeah, I didn't expect that to be included here.  I just moved code around in dev-scripts to demonstrate that it wouldn't have mattered if we did the exit since we don't do anything after the exit, and before resuming the installer as of this patch.  This is safe to go in without the kni-installer patch.

**Comment by metal3ci** [comment]
Build SUCCESS, see build http://10.8.144.11:8080/job/dev-tools/836/

**Pull request merged**
