### PR TITLE
AGENT-655: Use installer generated iPXE script

### PR DESCRIPTION
**Pull request by andfasano**
This patch fixes the PXE boot setup, by using directly the iPXE boot file generated by the openshift-installer

### CODE REVIEW

**Comment by andfasano** [comment]
Required by https://github.com/openshift/release/pull/39907

**Review by rwsu — COMMENTED** [review]
/lgtm

**Comment by andfasano** [comment]
skipping metal-ipi-serial-ipv4 failure, since it seems unrelated with the current patch

/override e2e-metal-ipi-serial-ipv4

**Pull request merged**
