### PR TITLE
multi-cluster: move messages to stderr

### PR DESCRIPTION
**Pull request by dhellmann**
Having common.sh echo messages to stdout interferes with scripts that
use config to find individual values.

### CODE REVIEW

**Comment by dhellmann** [comment]
@elfosardo I guess we could do that. It's really only the changes in common.sh that need it, and since it was just that file it seemed just as easy to add the redirection inline.

**Comment by metal3ci** [comment]
Build SUCCESS, see build http://10.8.144.11:8080/job/dev-tools/1704/

**Comment by dhellmann** [comment]
I went ahead and created an error function.

**Comment by metal3ci** [comment]
Build SUCCESS, see build http://10.8.144.11:8080/job/dev-tools/1710/

**Pull request merged**
