### PR TITLE
Rename 99_ manifesets to 98_ as workaround for MCO bug

### PR DESCRIPTION
**Pull request by stbenjam**
There's an ordering issue in MCO when using any custom manifests with
the 99_ prefix. Custom manifest until this is fixed should all start
with 98_ (or some lower number).

See https://github.com/openshift/machine-config-operator/pull/1756 for more explanation.

### CODE REVIEW

**Comment by hardys** [comment]
The job failed like `"error: failed to get vol 'ostest_master_0.qcow2'\nerror: Storage volume not found: no storage vol with matching path 'ostest_master_0.qcow2'",` - @derekhiggins @andfasano I think I saw some discussion of moving the pool to tmpfs or nvme, did that happen and could that be related?

**Comment by andfasano** [comment]
> The job failed like `"error: failed to get vol 'ostest_master_0.qcow2'\nerror: Storage volume not found: no storage vol with matching path 'ostest_master_0.qcow2'",` - @derekhiggins @andfasano I think I saw some discussion of moving the pool to tmpfs or nvme, did that happen and could that be related?

I don't think it was related, relaunching the job anyway

**Pull request merged**
