### PR TITLE
Make adjustments to latest changes from metal3-dev-env

### PR DESCRIPTION
**Pull request by russellb**

### CODE REVIEW

**Comment by metal3ci** [comment]
Build FAILURE, see build http://10.8.144.11:8080/job/dev-tools/1177/

**Comment by hardys** [comment]
the metal3-dev-env PR changes the format of the generated ironic_hosts.json so I think we need to modify the example `ironic_hosts.json.example` and jq query in `11_register_hosts.sh` to match?

Also the master_node_map_to_install_config function in `utils.sh`

It makes me wonder if we could make the change in metal3-dev-env a bit more backwards compatible tbh..

**Comment by hardys** [comment]
@russellb I pushed some changes which align to the new generated ironic_nodes.json format, works for me locally now.

I wonder if we should add some validation to catch anyone using a manually generated `$NODES_FILE` as they will need to update similarly?

**Comment by metal3ci** [comment]
Build ABORTED, see build http://10.8.144.11:8080/job/dev-tools/1178/

**Comment by hardys** [comment]
Actually the workers aren't deploying, I missed the change to address in `11_register_hosts.sh` - CI run aborted

**Comment by metal3ci** [comment]
Build ABORTED, see build http://10.8.144.11:8080/job/dev-tools/1179/

**Comment by hardys** [comment]
CI restarted at http://10.8.144.11:8080/job/dev-tools/1181/

**Comment by metal3ci** [comment]
Build SUCCESS, see build http://10.8.144.11:8080/job/dev-tools/1181/

**Pull request merged**
