### PR TITLE
Update metal3-dev-env hash to remove hack

### PR DESCRIPTION
**Pull request by elfosardo**
Remove metal3-dev-env hack as the new hash points to the fix:
https://github.com/metal3-io/metal3-dev-env/commit/868665523cb10ce723bce48ea4e9b22edcd68f68

### CODE REVIEW

**Comment by elfosardo** [comment]
probably missing a package
ERROR    Failed starting domain 'ostest_master_0': Path '/usr/share/OVMF/OVMF_CODE.fd' is not accessible: No such file or directory

**Comment by derekhiggins** [comment]
/lgtm
bm failure looks unrelated

**Comment by elfosardo** [comment]
/retest
giving one more try to pass, but failures are not related to this change

**Comment by elfosardo** [comment]
/override ci/prow/e2e-metal-ipi-serial-ipv4
unrelated known issue

**Comment by elfosardo** [comment]
/override ci/prow/e2e-metal-ipi-serial-ipv4
unrelated known issue

**Comment by elfosardo** [comment]
/override ci/prow/e2e-metal-ipi-bm
unrelated issue

**Pull request merged**
