### PR TITLE
NO-ISSUE Add VM_EXTRADISKS_LIST and VM_EXTRADISKS_SIZE

### PR DESCRIPTION
**Pull request by mkowalski**
This PR adds the ability to configure VM_EXTRADISKS_LIST and
VM_EXTRADISKS_SIZE that are required by the Assisted Service
to deploy the Local Storage Operator.

Configuration of the extra disks is automatically picked by the script
so that `storageClassDevices` in the `LocalVolume` manifest is filled
correctly with all the additional drives and does not require a manual
modification.

Co-authored-by: Lisa Rashidi-Ranjbar <lranjbar@redhat.com>

### CODE REVIEW

**Comment by mkowalski** [comment]
This PR supersedes https://github.com/openshift-metal3/dev-scripts/pull/1230

**Comment by flaper87** [comment]
Thanks @lranjbar and @mkowalski for the work here! 

/lgtm

**Comment by mkowalski** [comment]
CI error seems to be related to https://github.com/openshift-metal3/dev-scripts/pull/1230#issuecomment-832321054

```
[...]
"_raw_params": "dd if=/dev/zero of=/opt/dev-scripts/pool/ostest_master_0_.img bs=1 count=0 seek=\n",[0m
[...]
```

which is generated by https://github.com/metal3-io/metal3-dev-env/blob/master/vm-setup/roles/libvirt/tasks/vm_setup_tasks.yml#L90

**Review by flaper87 — APPROVED** [review]

**Review by djzager — APPROVED** [review]
Nice work.

**Pull request merged**
