### PR TITLE
Rename bmo-ironic-configmap to metal3-config.

### PR DESCRIPTION
**Pull request by imain**
metal3-config is a better name for the configmap and better
matches other configmap names.

### CODE REVIEW

**Comment by sadasu** [comment]
Yes, the name of the configmap matches what was just merged into MAO via https://github.com/openshift/machine-api-operator/pull/302. Thanks for making the corresponding change here.

**Comment by dhellmann** [comment]
Waiting for CI http://10.8.144.11:8080/job/dev-tools/1008/

**Comment by metal3ci** [comment]
Build SUCCESS, see build http://10.8.144.11:8080/job/dev-tools/1008/

**Pull request merged**
