### PR TITLE
Cleanup parts of dual-stack VIPs logic

### PR DESCRIPTION
**Pull request by creydr**
Addressing some nits from #1467 and (hopefully) making dual-stack VIPs logic a bit easier to read.

### CODE REVIEW

**Comment by bfournie** [comment]
When testing with just IPv6 (not dual-stack) this fixes the issue I was seeing from the previous PR:
/home/stack/dev-scripts-bfournie/network.sh: line 232: API_VIPs: unbound variable
+(/home/stack/dev-scripts-bfournie/network.sh:232): get_vips(): API_VIPs=

But I'm seeing a new problem:
+(/home/stack/dev-scripts-bfournie/network.sh:233): get_vips(): INGRESS_VIPS_V6=fd2e:6f44:5dd8:c956::4
/home/stack/dev-scripts-bfournie/network.sh: line 236: API_VIPS_V4: unbound variable
+(/home/stack/dev-scripts-bfournie/network.sh:236): get_vips(): API_VIPS=

Looks like need to add logic to handle the non dual-stack cases

**Comment by creydr** [comment]
> When testing with just IPv6 (not dual-stack) this fixes the issue I was seeing from the previous PR: /home/stack/dev-scripts-bfournie/network.sh: line 232: API_VIPs: unbound variable +(/home/stack/dev-scripts-bfournie/network.sh:232): get_vips(): API_VIPs=
> 
> But I'm seeing a new problem: +(/home/stack/dev-scripts-bfournie/network.sh:233): get_vips(): INGRESS_VIPS_V6=fd2e:6f44:5dd8:c956::4 /home/stack/dev-scripts-bfournie/network.sh: line 236: API_VIPS_V4: unbound variable +(/home/stack/dev-scripts-bfournie/network.sh:236): get_vips(): API_VIPS=
> 
> Looks like need to add logic to handle the non dual-stack cases

@bfournie can you give more details about your setup and where you saw the issue?

**Comment by bfournie** [comment]
> > When testing with just IPv6 (not dual-stack) this fixes the issue I was seeing from the previous PR: /home/stack/dev-scripts-bfournie/network.sh: line 232: API_VIPs: unbound variable +(/home/stack/dev-scripts-bfournie/network.sh:232): get_vips(): API_VIPs=
> > But I'm seeing a new problem: +(/home/stack/dev-scripts-bfournie/network.sh:233): get_vips(): INGRESS_VIPS_V6=fd2e:6f44:5dd8:c956::4 /home/stack/dev-scripts-bfournie/network.sh: line 236: API_VIPS_V4: unbound variable +(/home/stack/dev-scripts-bfournie/network.sh:236): get_vips(): API_VIPS=
> > Looks like need to add logic to handle the non dual-stack cases
> 
> @bfournie can you give more details about your setup and where you saw the issue? I saw at the beginning of #1467 in the `e2e-agent-compact` tests some of these issues, but they should have been fixed thinking

Hi, I'm testing agent with:
export AGENT_E2E_TEST_SCENARIO=COMPACT_IPV6

In network.sh, I see API_VIPS being used before its set:
+(/home/stack/dev-scripts-bfournie/network.sh:231): get_vips(): [[ -n fd2e:6f44:5dd8:c956::/64 ]]
/home/stack/dev-scripts-bfournie/network.sh: line 232: API_VIPS: unbound variable

It looks like get_vips() is called in set_api_and_ingress_vip() before API_VIPS is set and if just using V6 it uses it before being set. Its OK for dual stack since its set for V4

**Comment by creydr** [comment]
/hold 
until we get the confirmation from @bfournie that it works with agent on single stack too

**Comment by bfournie** [comment]
The latest commit fixes the issue I was having with IPv6, now seeing
```
                   "apiVIPs": [
                        "fd2e:6f44:5dd8:c956::5"
                    ],
                    "ingressVIPs": [
                        "fd2e:6f44:5dd8:c956::4"
                    ]
```

/lgtm

**Comment by creydr** [comment]
@cybertron could you PTAL at this PR?
Thanks in advance

**Comment by cybertron** [comment]
/approve

Passing ci and I verified the dualstack behavior locally so we should be good!

**Pull request merged**
