### PR TITLE
Remove ingress controller manifest.

### PR DESCRIPTION
**Pull request by russellb**
This is no longer required, as we install a 3 node cluster by default.
The installer will automatically adjust the scheduler configuration to
make master nodes schedulable. For more details on that change, see:
https://github.com/openshift/installer/pull/2004
    
Closes issue #705

### CODE REVIEW

**Comment by russellb** [comment]
This isn't working consistently for me locally.  It seems the machine-config-operator is not reliably acting on this value at startup.  I just had to edit the `mastersSchedulable: true` setting to `false` and back to `true` to trigger reconciliation

**Comment by russellb** [comment]
bug filed: https://github.com/openshift/machine-config-operator/issues/1024

**Comment by metal3ci** [comment]
Build FAILURE, see build http://10.8.144.11:8080/job/dev-tools/980/

**Comment by metal3ci** [comment]
Build FAILURE, see build http://10.8.144.11:8080/job/dev-tools/1032/

**Comment by metal3ci** [comment]
Build SUCCESS, see build http://10.8.144.11:8080/job/dev-tools/1063/

**Comment by hardys** [comment]
Ok this looks good now since the latest rebase, @russellb if you're happy we can go ahead and land this?

**Comment by russellb** [comment]
I've rebased this and updated the commit message to reflect what was remaining.  Let's let CI run once more ...

**Comment by metal3ci** [comment]
Build FAILURE, see build http://10.8.144.11:8080/job/dev-tools/1064/

**Comment by metal3ci** [comment]
Build SUCCESS, see build http://10.8.144.11:8080/job/dev-tools/1070/

**Pull request merged**
