### PR TITLE
Make number of workers configurable

### PR DESCRIPTION
**Pull request by hardys**
This removes the previous VM_NODES_FILE interface, so that we can dynamically
generate the data for master/worker nodes, and avoid issues where previous hard
coded things weren't updated via VM_NODES_FILE.

Instead, you can now pass NUM_MASTERS, NUM_WORKERS and VM_EXTRADISKS variables
to control the number of master/worker nodes, and if we create an extra disk
for ceph.

The previous cleanup in host_cleanup also didn't consider VM_NODES_FILE,
so that is updated to align with this new approach, fixing bug #487

Closes: #487
Related: #486

### CODE REVIEW

**Comment by gklein** [comment]
I've tested this PR with:
```
export NUM_MASTERS="3"
export NUM_WORKERS="3"
export VM_EXTRADISKS="true"
````
Everything seems to work as expected, but it seems the workers only started a few minutes after the deployment was already done. 

I suggest we consider adding some logic to wait for the workers to appear before declaring that the deployment has completed.

**Comment by hardys** [comment]
I looked at waiting for multiple workers, and it looks like it's difficult ref https://github.com/openshift-metal3/dev-scripts/issues/421 so I'd suggest we go ahead with this and figure out the solution as a follow-up?

**Comment by derekhiggins** [comment]
Build FAILURE, see build http://10.8.144.11:8080/job/dev-tools/611/

**Comment by russellb** [comment]
CI failed as the service we're grabbing RHCOS images from is down

**Comment by russellb** [comment]
Tested this locally and it's working fine for me.  Thanks!

**Pull request merged**
