### PR TITLE
Enable configuring specific specs for extraworkers

### PR DESCRIPTION
**Pull request by osherdp**
Added another flavor ``extraworker`` so that we can configure memory, vCPUs count, and disk size for extra workers.

### CODE REVIEW

**Review by elfosardo — APPROVED** [review]

**Review by cybertron — APPROVED** [review]
/lgtm

Seems fine to me. Default behavior should be the same as before, but this provides a little extra flexibility for configuring the extra workers.

**Comment by osherdp** [comment]
@elfosardo @cybertron can any of you approve?
Thanks in advance guys! 😁

**Pull request merged**
