### PR TITLE
Another attempt to update Ansible and metal3-dev-env

### PR DESCRIPTION
**Pull request by dtantsur**
The previous one got reverted because it did not account for certain variable changes.

### CODE REVIEW

**Comment by elfosardo** [comment]
do we want to add the migration to ansible 7 here or open a new PR?
Looking at the logs this passed with the offending change, so it looks good

**Comment by honza** [comment]
Do we want a newer version of metal3-dev-env?  It currently points to a [version](https://github.com/metal3-io/metal3-dev-env/commit/a994b1447f89e20ec9cc161700a9e829fd5d4b89) from April 2023.

**Comment by dtantsur** [comment]
> Do we want a newer version of metal3-dev-env? It currently points to a [version](https://github.com/metal3-io/metal3-dev-env/commit/a994b1447f89e20ec9cc161700a9e829fd5d4b89) from April 2023.

One step at a time, okay? :) We already have an idea what breaks with this version, the next one will probably need more investigation.

**Comment by elfosardo** [comment]
/retest
failure does not look related

**Comment by elfosardo** [comment]
/retest
timeout in ipv4

**Comment by elfosardo** [comment]
/hold
let's wait for the weekend :)

**Pull request merged**
