### PR TITLE
Bump metal3-dev-env version

### PR DESCRIPTION
**Pull request by hardys**
So we pick up https://github.com/metal3-io/metal3-dev-env/pull/619

This is needed for testing live-iso install ref #1193 since that needs
the sushy_ignore_boot_device option

### CODE REVIEW

**Comment by stbenjam** [comment]
```
[36mINFO[0m[2021-04-13T12:34:44Z] +(./01_install_requirements.sh:27): main(): ansible-galaxy install -r vm-setup/requirements.yml 
[36mINFO[0m[2021-04-13T12:34:44Z] ./01_install_requirements.sh: line 27: ansible-galaxy: command not found 
```

Looks like maybe we need to grab ansible-galaxy

**Comment by hardys** [comment]
> Looks like maybe we need to grab ansible-galaxy

Hmm yeah, looking again at https://github.com/metal3-io/metal3-dev-env/pull/574 I think there's some other logic we need e.g enabling the repo to install ansible etc

centos_install_requirements.sh actually enabled ansible-2-for-rhel-8-x86_64-rpms but then did a pip install of ansible which is weird, probably it'd be better if both dev-scripts and metal3-dev-env did a package install instead :thinking:

**Comment by hardys** [comment]
Ok I copied what I think is the minimum from the now-deleted centos_install_requirements.sh, hopefully that fixes CI

**Comment by hardys** [comment]
Hmm, both CI tests failed connecting to the local registry, but even after a registry_cleanup I can't reproduce locally - rechecking to confirm if it's a flake or something related to the PR

**Comment by stbenjam** [comment]
/etc/hosts never gets the entry for the registry. This seems to be the problem:

```
[36mINFO[0m[2021-04-13T17:07:52Z] +++(network.sh:7): nth_ip(): python -c 'from ansible.plugins.filter import ipaddr; print(ipaddr.nthhost('\''fd2e:6f44:5dd8:c956::/120'\'', 1))' 
[36mINFO[0m[2021-04-13T17:07:52Z] network.sh: line 7: python: command not found 
[36mINFO[0m[2021-04-13T17:07:52Z] ++(network.sh:136): source(): export PROVISIONING_HOST_EXTERNAL_IP= 
[36mINFO[0m[2021-04-13T17:07:52Z] ++(network.sh:136): source(): PROVISIONING_HOST_EXTERNAL_IP= 
```

Is it python3 now?

**Comment by hardys** [comment]
> Is the binary python3 now?

Oh thanks, I missed that - the issue is `sudo alternatives --set python /usr/bin/python3` was called previously from `centos_install_requirements.sh`

I'll add it here, but probably some of these changes should be reinstated in metal3-dev-env for centos/rhel8 users too.

**Comment by hardys** [comment]
I think this is good now @stbenjam - thanks for the help figuring out the issues.

As a follow-up I'll take a look at if we need any similar changes to metal3-dev-env

**Comment by stbenjam** [comment]
/test e2e-metal-ipi

CI is currently failing with some dep problems, curious if maybe the metal3-dev-env changes fix it since centos_requirements was replaced

**Comment by hardys** [comment]
I updated to account for https://github.com/openshift-metal3/dev-scripts/pull/1225 but now see #1229 so I'll hold until that merges then update again

**Pull request merged**
