### PR TITLE
multi-cluster: make it possible to change the docker registry image

### PR DESCRIPTION
**Pull request by dhellmann**
The latest image has a bug that prevents mirroring some images, so
make it possible to specify an older version.

### CODE REVIEW

**Comment by metal3ci** [comment]
Build FAILURE, see build http://10.8.144.11:8080/job/dev-tools/1672/

**Comment by metal3ci** [comment]
Build FAILURE, see build http://10.8.144.11:8080/job/dev-tools/1683/

**Comment by metal3ci** [comment]
Build FAILURE, see build http://10.8.144.11:8080/job/dev-tools/1685/

**Comment by metal3ci** [comment]
Build FAILURE, see build http://10.8.144.11:8080/job/dev-tools/1690/

**Comment by metal3ci** [comment]
Build SUCCESS, see build http://10.8.144.11:8080/job/dev-tools/1696/

**Comment by russellb** [comment]
you could add this to the sample config (config_example.sh), but otherwise LGTM

**Pull request merged**
