### PR TITLE
Update MetalLB README file and Makefile rules to reflect the latest configuration changes

### PR DESCRIPTION
**Pull request by sabinaaledort**
Update MetalLB README file and Makefile rules to reflect the latest configuration changes (the deployment method change and the E2E tests run).

https://github.com/openshift-metal3/dev-scripts/pull/1302
https://github.com/openshift-metal3/dev-scripts/pull/1305

### CODE REVIEW

**Comment by hardys** [comment]
/ok-to-test
/retitle Update MetalLB README file and Makefile rules to reflect the latest configuration changes

(you might like to fix the corresponding typo in the commit message)

**Comment by sabinaaledort** [comment]
> /ok-to-test /retitle Update MetalLB README file and Makefile rules to reflect the latest configuration changes
> 
> (you might like to fix the corresponding typo in the commit message)

thanks!

**Comment by sabinaaledort** [comment]
/retest
origin-tests failed (unrelated to my change)

**Comment by sabinaaledort** [comment]
/test e2e-metal-ipi
origin-tests failed (unrelated to my change)

**Comment by sabinaaledort** [comment]
/test e2e-metal-ipi
origin-tests failed (unrelated to my change)

**Comment by sabinaaledort** [comment]
/test e2e-metal-ipi-ovn-ipv6
origin-tests failed (unrelated to my change)

**Pull request merged**
