### PR TITLE
Doc: default release is now 4.12

### PR DESCRIPTION
**Pull request by flavio-fernandes**
TRIVIAL: Update docs and add a comment in common.sh as a reminder when default value changes.

This is a minor cont to https://github.com/openshift-metal3/dev-scripts/pull/1459

Signed-off-by: Flavio Fernandes <flaviof@redhat.com>

### CODE REVIEW

**Comment by flavio-fernandes** [comment]
@dougsland PTAL :)

**Comment by cybertron** [comment]
/approve

This is a doc-only change so there's no need to spend ci cycles retesting it.

**Comment by derekhiggins** [comment]
/override ci/prow/e2e-agent-sno-ipv6 ci/prow/e2e-metal-ipi-ovn-ipv6 ci/prow/e2e-metal-ipi-virtualmedia ci/prow/e2e-metal-ipi-ovn-dualstack

**Pull request merged**
