### PR TITLE
Caching

### PR DESCRIPTION
**Pull request by derekhiggins**
Some caching fixups for CI

### CODE REVIEW

**Comment by metal3ci** [comment]
Build SUCCESS, see build http://10.8.144.11:8080/job/dev-tools/1569/

**Comment by metal3ci** [comment]
Build FAILURE, see build http://10.8.144.11:8080/job/dev-tools/1570/

**Comment by metal3ci** [comment]
Build FAILURE, see build http://10.8.144.11:8080/job/dev-tools/1571/

**Comment by metal3ci** [comment]
Build SUCCESS, see build http://10.8.144.11:8080/job/dev-tools/1573/

**Comment by derekhiggins** [comment]
> Build SUCCESS, see build http://10.8.144.11:8080/job/dev-tools/1573/

**Comment by derekhiggins** [comment]
Closed by accident, reopened here https://github.com/openshift-metal3/dev-scripts/pull/963

**Pull request closed without merging**
