### PR TITLE
[WIP] Rebase on 4.2.0-0.ci-2019-07-03-145946

### PR DESCRIPTION
**Pull request by stbenjam**
- Checkout https://github.com/openshift-metal3/kni-installer/pull/129/files to $GOPATH/src/github.com/openshift-metalkube/kni-installer
- Checkout this PR
- Run `TF_LOG=trace KNI_INSTALL_FROM_GIT=true make`

### CODE REVIEW

**Comment by hardys** [comment]
I tested this locally, and while it does work, I've seen timeouts waiting for the CVO to finish, then eventually it does complete, e.g:

```
$ oc describe clusterversion
...
  Conditions:
    Last Transition Time:  2019-07-04T14:43:08Z
    Message:               Done applying 4.2.0-0.ci-2019-07-03-145946
    Status:                True
    Type:                  Available
    Last Transition Time:  2019-07-04T14:37:45Z
    Status:                False
    Type:                  Failing
    Last Transition Time:  2019-07-04T14:43:08Z
    Message:               Cluster version is 4.2.0-0.ci-2019-07-03-145946
    Status:                False
    Type:                  Progressing
    Last Transition Time:  2019-07-04T14:12:31Z
    Message:               Unable to retrieve available updates: currently installed version 4.2.0-0.ci-2019-07-03-145946 not found in the "stable-4.2" channel
    Reason:                RemoteFailed
    Status:                False
    Type:                  RetrievedUpdates
  Desired:
    Force:    false
    Image:    registry.svc.ci.openshift.org/ocp/release@sha256:cecf43342b341d1d17029251f3ca35472a34f17e3590e09099e74ea721471bd6
    Version:  4.2.0-0.ci-2019-07-03-145946
  History:
    Completion Time:    2019-07-04T14:43:08Z
    Image:              registry.svc.ci.openshift.org/ocp/release@sha256:cecf43342b341d1d17029251f3ca35472a34f17e3590e09099e74ea721471bd6
    Started Time:       2019-07-04T14:12:31Z
    State:              Completed
    Verified:           false
    Version:            4.2.0-0.ci-2019-07-03-145946
  Observed Generation:  1
  Version Hash:         rXikriX1Jz4=
Events:                 <none>

$ oc get clusterversion
NAME      VERSION                        AVAILABLE   PROGRESSING   SINCE   STATUS
version   4.2.0-0.ci-2019-07-03-145946   True        False         3m31s   Cluster version is 4.2.0-0.ci-2019-07-03-145946

```

So there seems to be a long delay where the CVO can't retrieve the desired updates, and eventually it works, so I guess there's a dependency on some other operator but not figured out what yet.

**Comment by markmc** [comment]
Ok, with a rebase to latest master, this worked for me

**Comment by markmc** [comment]
> I tested this locally, and while it does work, I've seen timeouts waiting for the CVO to finish, then eventually it does complete, e.g:
> 
> ```
> $ oc describe clusterversion
> ...
>   Conditions:
>     Last Transition Time:  2019-07-04T14:43:08Z
>     Message:               Done applying 4.2.0-0.ci-2019-07-03-145946
>     Status:                True
>     Type:                  Available
>     Last Transition Time:  2019-07-04T14:37:45Z
>     Status:                False
>     Type:                  Failing
>     Last Transition Time:  2019-07-04T14:43:08Z
>     Message:               Cluster version is 4.2.0-0.ci-2019-07-03-145946
>     Status:                False
>     Type:                  Progressing
>     Last Transition Time:  2019-07-04T14:12:31Z
>     Message:               Unable to retrieve available updates: currently installed version 4.2.0-0.ci-2019-07-03-145946 not found in the "stable-4.2" channel
>     Reason:                RemoteFailed
>     Status:                False
>     Type:                  RetrievedUpdates
>   Desired:
>     Force:    false
>     Image:    registry.svc.ci.openshift.org/ocp/release@sha256:cecf43342b341d1d17029251f3ca35472a34f17e3590e09099e74ea721471bd6
>     Version:  4.2.0-0.ci-2019-07-03-145946
>   History:
>     Completion Time:    2019-07-04T14:43:08Z
>     Image:              registry.svc.ci.openshift.org/ocp/release@sha256:cecf43342b341d1d17029251f3ca35472a34f17e3590e09099e74ea721471bd6
>     Started Time:       2019-07-04T14:12:31Z
>     State:              Completed
>     Verified:           false
>     Version:            4.2.0-0.ci-2019-07-03-145946
>   Observed Generation:  1
>   Version Hash:         rXikriX1Jz4=
> Events:                 <none>
> 
> $ oc get clusterversion
> NAME      VERSION                        AVAILABLE   PROGRESSING   SINCE   STATUS
> version   4.2.0-0.ci-2019-07-03-145946   True        False         3m31s   Cluster version is 4.2.0-0.ci-2019-07-03-145946
> ```
> 
> So there seems to be a long delay where the CVO can't retrieve the desired updates, and eventually it works, so I guess there's a dependency on some other operator but not figured out what yet.

What I saw was it was waiting the longest for the authentication operator to complete ... looking at the logs, I'm not seeing anything glaringly obvious as specific to baremetal

**Comment by hardys** [comment]
https://github.com/openshift-metal3/dev-scripts/pull/654 landed so I'll close this one

**Pull request closed without merging**
