### PR TITLE
Remove tmp files with a trap

### PR DESCRIPTION
**Pull request by derekhiggins**
These were getting left behind on failure.

### CODE REVIEW

**Comment by hardys** [comment]
Thanks looks good but this is also happening in the extract_command function from `ocp_install_env.sh`  - called via extract_oc and extract_installer in `03_build_installer.sh`

Could we perhaps also fix that by moving the function and variable declaration into one of the common files that get sourced?

**Comment by derekhiggins** [comment]
> Thanks looks good but this is also happening in the extract_command function from `ocp_install_env.sh` - called via extract_oc and extract_installer in `03_build_installer.sh`
> 
> Could we perhaps also fix that by moving the function and variable declaration into one of the common files that get sourced?

New version pushed up, untested but will check CI logs.

**Comment by metal3ci** [comment]
Build FAILURE, see build http://10.8.144.11:8080/job/dev-tools/1667/

**Comment by metal3ci** [comment]
Build SUCCESS, see build http://10.8.144.11:8080/job/dev-tools/1668/

**Comment by derekhiggins** [comment]
> Build SUCCESS, see build http://10.8.144.11:8080/job/dev-tools/1668/

Looks ok
```
+(utils.sh:365): removetmp(): rm -rf installer--OXnOAYM1KZ installer--0lO1r0gMWV pullsecret--nMkaidG3zv installer--QjCY3LJGRY pullsecret--NHxp4rCJXw pullsecret--nHLjSYYgEt
...
+(utils.sh:365): removetmp(): rm -rf pullsecret--GnlhfIy6Ov combined-pullsecret--gTvcuxvkSt release-update--7GypuEeuHm mirror-installer--X9y1OvGMqv

```

**Pull request merged**
