### PR TITLE
Rebase on 4.2.0-0.ci-2019-06-19-140700

### PR DESCRIPTION
**Pull request by stbenjam**
To test

- Check out this PR
- Check out https://github.com/openshift-metal3/kni-installer/pull/106 to `~/go/src/github.com/openshift-metalkube/kni-installer`
- Install with `KNI_INSTALL_FROM_GIT=true make`

Will build a KNI release image when installer PR is merged.

### CODE REVIEW

**Comment by stbenjam** [comment]
FWIW, I wouldn't try this yet, the rebase has some issues still

**Comment by stbenjam** [comment]
I've built the image.  I've also requested openshift team to pin this release, I think if CI passes we can merge it as soon as we get confirmation it's pinned.

**Comment by metal3ci** [comment]
Build FAILURE, see build http://10.8.144.11:8080/job/dev-tools/778/

**Comment by hardys** [comment]
Hmm the CI failure looks real, for some reason I don't see the coredns and dns prepender stuff in the journal output of the masters - attempting to reproduce locally.

**Comment by hardys** [comment]
Ok I see the same problem locally - for some reason the manifests we're adding are not picked up so none of the coredns/keepalived stuff is running on the masters...

**Comment by stbenjam** [comment]
I believe https://github.com/openshift-metal3/kni-installer/pull/116 broke it.

With the correct annotation, the data generated in https://github.com/openshift-metal3/kni-installer/blob/master/pkg/asset/machines/master.go#L160 is now being used, before it was under the openstack key so it wasn't being looked at.

**Comment by metal3ci** [comment]
Build SUCCESS, see build http://10.8.144.11:8080/job/dev-tools/782/

**Comment by stbenjam** [comment]
The release is pinned and CI is green, going to merge this

**Pull request merged**
