### PR TITLE
Power down redfish bm nodes before provisioning

### PR DESCRIPTION
**Pull request by derekhiggins**

### CODE REVIEW

**Comment by cybertron** [comment]
Redfish is our default now, right? So the passing ci jobs mean this is working?

**Comment by derekhiggins** [comment]
> Redfish is our default now, right? So the passing ci jobs mean this is working?

It isn't used in CI because its wrapped in
> if [[ "${NODES_PLATFORM}" == "baremetal" ]] && [ -n "$NODES_FILE" ] ; then

in CI NODES_PLATFORM == libvirt 

but I have been using this in a baremetal env and all is working

**Comment by derekhiggins** [comment]
/override ci/prow/e2e-agent-compact-ipv4

log gather failure, unrelated and this PR isn't tested in the job

**Pull request merged**
