### PR TITLE
WIP: deploy solution within cluster to autosign certs

### PR DESCRIPTION
**Pull request by karmab**
As a temporary solution, we provide an artifact which will autosign certs each 5 minutes after initial deployment

### CODE REVIEW

**Comment by russellb** [comment]
Take a look at this script - https://github.com/openshift/openshift-ansible/blob/release-3.11/roles/openshift_bootstrap_autoapprover/files/openshift-bootstrap-controller.yaml

what do you think about adapting that?

**Comment by russellb** [comment]
also - if we switch to something in cluster, we can drop the cron job from the provisioning host

**Comment by karmab** [comment]
> https://github.com/openshift/openshift-ansible/blob/release-3.11/roles/openshift_bootstrap_autoapprover/files/openshift-bootstrap-controller.yaml

actually, i had a look at this first, but it seems to be:
- specific to 3.11
- missing the image name
- too complex for a simple task

**Comment by russellb** [comment]
> > https://github.com/openshift/openshift-ansible/blob/release-3.11/roles/openshift_bootstrap_autoapprover/files/openshift-bootstrap-controller.yaml
> 
> actually, i had a look at this first, but it seems to be:
> 
>     * specific to 3.11
> 
>     * missing the image name

I said adapt, not copy verbatim :-)

>     * too complex for a simple task

Well, I disagree.  I like the `oc observe` approach better, as it will react to any CSRs immediately instead of checking ever N minutes.

**Comment by karmab** [comment]
@russellb provided an adaptation of the statefulset (untested though)

**Pull request closed without merging**
