### PR TITLE
run_ci.sh: move things around to happen in the correct order

### PR DESCRIPTION
**Pull request by derekhiggins**
We need to clone project directories first
then set variables based on what directories exist
then import common.sh

### CODE REVIEW

**Comment by metal3ci** [comment]
Build FAILURE, see build http://10.8.144.11:8080/job/dev-tools/1217/

**Comment by metal3ci** [comment]
Build SUCCESS, see build http://10.8.144.11:8080/job/dev-tools/1226/

**Comment by metal3ci** [comment]
Build FAILURE, see build http://10.8.144.11:8080/job/dev-tools/1228/

**Comment by metal3ci** [comment]
Build FAILURE, see build http://10.8.144.11:8080/job/dev-tools/1229/

**Comment by metal3ci** [comment]
Build ABORTED, see build http://10.8.144.11:8080/job/dev-tools/1230/

**Comment by stbenjam** [comment]
Failure was unrelated, thanks!

**Comment by metal3ci** [comment]
Build ABORTED, see build http://10.8.144.11:8080/job/dev-tools/1233/

**Pull request merged**
