### PR TITLE
using registry image pulled from quay.io registry

### PR DESCRIPTION
**Pull request by osherdp**
docker.io rate limiter is too restrictive.

### CODE REVIEW

**Comment by stbenjam** [comment]
I'm not sure I want to rely on someone's personally maintained copy which is potentially quite out of date -- you can override this in your own config_XXXXXX.sh:

```bash
export DOCKER_REGISTRY_IMAGE=quay.io/kirankt/registry:latest
```

I haven't heard too many complaints about the rate limiting lately to make the overhead of maintaining a mirror worthwhile.

**Comment by osherdp** [comment]
I wouldn't pass on that, you might also have a lot of unsatisfied users that just walk away when they have too many flakes
Maybe we can do an automatic mirroring to some official repository? https://access.redhat.com/documentation/en-us/red_hat_quay/3/html/manage_red_hat_quay/repo-mirroring-in-red-hat-quay

**Comment by osherdp** [comment]
@celebdor wdyt?

**Comment by stbenjam** [comment]
> I wouldn't pass on that, you might also have a lot of unsatisfied users that just walk away when they have too many flakes

There's no evidence of that happening? You're the first I've seen hit the rate limiting in a while.  If you're willing to setup a mirror and maintain it, I'd be more willing to accept this change, or get @kirankt to confirm he'll maintain his copy.

**Comment by stbenjam** [comment]
There is also `quay.io/libpod/registry` maintained by the podman project. It's not fully up to date but that's probably more reliable than relying on a personal mirror.

**Comment by kirankt** [comment]
> > I wouldn't pass on that, you might also have a lot of unsatisfied users that just walk away when they have too many flakes
> 
> There's no evidence of that happening? You're the first I've seen hit the rate limiting in a while. If you're willing to setup a mirror and maintain it, I'd be more willing to accept this change, or get @kirankt to confirm he'll maintain his copy.

I agree with @stbenjam that the rate limiting problem has been a non-issue lately. I only keep a copy in my quay repo just so that I could use the `DOCKER_REGISTRY_IMAGE` when it does indeed show up. I personally don't think the change this PR is proposing should be permanently pointing to a personal repo.

**Comment by osherdp** [comment]
@stbenjam @kirankt done, changed to the libpod image

**Comment by hardys** [comment]
I have hit this issue several times locally, so have been using the image from @kirankt as a workaround - I'm unclear why we don't hit the problem in CI though.

So I'm fine with this, although I think long term we should look at moving away from the docker registry completely, and instead run a local quay instance: https://docs.projectquay.io/deploy_quay.html

That is a little more complex than the docker setup though - IIRC @andfasano took a look into it, but we still need to figure out some details like how to configure TLS in the same way as the current setup.

**Comment by andfasano** [comment]
@hroyrh is currently working on the local quay analysis, anyhow from a preliminary check didn't appear to be easily adopted. The `libpod` repo seems a reasonable compromise in the meantime.

**Comment by andfasano** [comment]
@osherdp can you please squash the commits?

**Comment by osherdp** [comment]
@andfasano done

**Comment by celebdor** [comment]
> I have hit this issue several times locally, so have been using the image from @kirankt as a workaround - I'm unclear why we don't hit the problem in CI though.
> 
> So I'm fine with this, although I think long term we should look at moving away from the docker registry completely, and instead run a local quay instance: https://docs.projectquay.io/deploy_quay.html
> 
> That is a little more complex than the docker setup though - IIRC @andfasano took a look into it, but we still need to figure out some details like how to configure TLS in the same way as the current setup.

I suspect the CI must have a Docker subscription to prevent such rate limiting issues.

**Pull request merged**
