### PR TITLE
AGENT-350: Run agent_gather on the hosts

### PR DESCRIPTION
**Pull request by pawanpinjarkar**
Signed-off-by: Pawan Pinjarkar <ppinjark@redhat.com>

### CODE REVIEW

**Comment by pawanpinjarkar** [comment]
depends on https://github.com/openshift/installer/pull/6683

**Comment by zaneb** [comment]
> depends on [openshift/installer#6683](https://github.com/openshift/installer/pull/6683)

And also a backport before we can use it in the CI jobs.

The more I think about it, the more I think the right thing for CI specifically is to run agent-gather on _all_ of the hosts. We may need e.g. the log from a host that is not node0 to debug something.

**Comment by pawanpinjarkar** [comment]
> openshift/installer#6683

As this PR is now to run agent gather on all the hosts, it does not depend on https://github.com/openshift/installer/pull/6683

**Pull request merged**
