### PR TITLE
OCPBUGS-18078: Clean dnf data before system upgrade

### PR DESCRIPTION
**Pull request by elfosardo**
It can help in case of cache and metadata issues, as well as local
dnf db shenanighans.

Also use nobest option for dnf upgrade.

### CODE REVIEW

**Comment by bfournie** [comment]
I ran into this issue yesterday too
/lgtm

**Comment by elfosardo** [comment]
the latest failures didn't have the final version of the patch, weird
anyway the current failure in ci/prow/e2e-agent-compact-ipv4 seems infra related

**Comment by ncdc** [comment]
Agree that the failures in e2e-agent-compact-ipv4 are not related to this PR

**Comment by derekhiggins** [comment]
/override ci/prow/e2e-metal-ipi-serial-ipv4 

Also about to fail on unrelated problems

**Pull request merged**
