### PR TITLE
Don't force use of a mirrored image in v6-primary

### PR DESCRIPTION
**Pull request by cybertron**
It isn't necessary to use a mirror with v6-primary since it's still dual stack and still has access to v4 public registries. By forcing the use of the mirrored image path, we actually break the no mirror use case because we point the deployment at an image that doesn't exist in the local registry.

### CODE REVIEW

**Review by mkowalski — APPROVED** [review]

**Comment by elfosardo** [comment]
/override ci/prow/e2e-agent-ha-dualstack ci/prow/e2e-metal-ipi-virtualmedia
not really needed for this change

**Comment by elfosardo** [comment]
/override ci/prow/e2e-metal-ipi-serial-ipv4
failure looks related to an issue with a storage operator

**Pull request merged**
