### PR TITLE
rename metalkube to metal3

### PR DESCRIPTION
**Pull request by dhellmann**
Also includes some quay.io image name changes

### CODE REVIEW

**Comment by derekhiggins** [comment]
Build FAILURE, see build http://10.8.144.11:8080/job/dev-tools/597/

**Comment by derekhiggins** [comment]
> Build FAILURE, see build http://10.8.144.11:8080/job/dev-tools/597/

Looks like the merge conflict caused the failure

> + git pull --no-edit https://github.com/dhellmann/dev-scripts metal3-rename
> ... Automatic merge failed; fix conflicts and then commit the result.

**Comment by derekhiggins** [comment]
Build FAILURE, see build http://10.8.144.11:8080/job/dev-tools/604/

**Comment by dantrainor** [comment]
I came across this as I was trying to troubleshoot my deployments.  I noticed that some files mentioned here (assets/files/etc/kubernetes/manifests/*) use 'openshift-metalkube' quay repos, and upon further investigation are old (relatively speaking) to the new containers located in the 'openshift-metal3' repository.

In the build failure, I saw:

Apr 24 18:15:19 |  +++ jq -r .baseURI /home/notstack/go/src/github.com/openshift-metal3/kni-installer/data/data/rhcos.json
Apr 24 18:15:19 |  jq: error: Could not open file /home/notstack/go/src/github.com/openshift-metal3/kni-installer/data/data/rhcos.json: No such file or directory
Apr 24 18:15:19 |  ++ export RHCOS_INSTALLER_IMAGE_URL=
Apr 24 18:15:19 |  ++ RHCOS_INSTALLER_IMAGE_URL=
Apr 24 18:15:19 |  ++ export RHCOS_IMAGE_URL=
Apr 24 18:15:19 |  ++ RHCOS_IMAGE_URL=

I think there still be some files that reference the 'openshift-metalkube' github repo because at least in this example, rhcos.json resides in $GOPATH/src/github.com/openshift-metalkube/kni-installer/data/data/rhcos.json, not $GOPATH/src/github.com/openshift-metal3/kni-installer/data/data/rhcos.json.  This is because hack/build.sh also references openstack-metalkube and 'go get's a repo named openshift-metalkube accordingly.

I didn't test this particular PR because I was in the middle of a build when I came across it, but just manually changing the quay.io repository names to reflect the openshift-metal3 repo resulted in a successful deployment.  I'll pick this up shortly.

At this time I would say this is a pretty critical change necessary for deployments moving forward.

**Comment by dantrainor** [comment]
I broke my local git but in the meantime these were my simple changes to fix the merge conflict

https://github.com/dantrainor/dev-scripts/tree/metal3-rename

re: hack/build.sh changes, this exists in $GOPATH.  There might be a race condition where we see $GOPATH/src/github.com/openshift-metal3/kni-installer/hack/build.sh where if the unmodified version (the one that references the old repo name) already exists, it won't be changed to reference the new repo name.  Simply 'rm -rf ~/go' fixes this but we may want to change the behavior of https://github.com/openshift-metal3/dev-scripts/blob/master/03_ocp_repo_sync.sh#L10

**Comment by gklein** [comment]
> I broke my local git but in the meantime these were my simple changes to fix the merge conflict
> 
> https://github.com/dantrainor/dev-scripts/tree/metal3-rename
> 
> re: hack/build.sh changes, this exists in $GOPATH. There might be a race condition where we see $GOPATH/src/github.com/openshift-metal3/kni-installer/hack/build.sh where if the unmodified version (the one that references the old repo name) already exists, it won't be changed to reference the new repo name. Simply 'rm -rf ~/go' fixes this but we may want to change the behavior of https://github.com/openshift-metal3/dev-scripts/blob/master/03_ocp_repo_sync.sh#L10
To help prevent similar issues in the future, would it make sense to 'rm -rf ~/go' as part 
'host_cleanup.sh' so it will be covered by 'make clean' ?

**Comment by hardys** [comment]
> > I broke my local git but in the meantime these were my simple changes to fix the merge conflict
> > https://github.com/dantrainor/dev-scripts/tree/metal3-rename
> > re: hack/build.sh changes, this exists in $GOPATH. There might be a race condition where we see >$GOPATH/src/github.com/openshift-metal3/kni-installer/hack/build.sh where if the unmodified version >(the one that references the old repo name) already exists, it won't be changed to reference the new >repo name. Simply 'rm -rf ~/go' fixes this but we may want to change the behavior of >https://github.com/openshift-metal3/dev-scripts/blob/master/03_ocp_repo_sync.sh#L10
> 
> To help prevent similar issues in the future, would it make sense to 'rm -rf ~/go' as part
> 'host_cleanup.sh' so it will be covered by 'make clean' ?

IMO we shouldn't do that, or folks doing development run the risk of losing all their work from ~/go/src ;)

Perhaps we either mention cleaning it in the commit message as a manual step, or do something more fancy by looking at the remotes for existing repos and where necessary changing them?

I'm not entirely clear on the race condition comment tbh, but for a one-time rename like this, I think a documented manual cleanup would be acceptable.

**Comment by russellb** [comment]
I'd like to finish fixing #548 as a next step here, which will get us on the metal3 version of baremetal-operator, and then we can look at changing the rest

**Comment by stbenjam** [comment]
We've largely renamed everything already, with a few small exceptions, is this PR needed anymore? Going to close this, feel free to update and re-open if needed.

**Pull request closed without merging**
