### PR TITLE
Bump dev-scripts to 4.8

### PR DESCRIPTION
**Pull request by stbenjam**
This changes the default development version to 4.8.

### CODE REVIEW

**Comment by stbenjam** [comment]
Let's wait for a new accepted build: https://openshift-release.apps.ci.l2s4.p1.openshiftapps.com/#4.8.0-0.nightly


/hold

**Comment by stbenjam** [comment]
There are green 4.8 nightlies.

/hold cancel

**Review by asalkeld — COMMENTED** [review]
/lgtm

**Pull request merged**
