### PR TITLE
Run some of openshift CI on installer PR's

### PR DESCRIPTION
**Pull request by stbenjam**
As we now have an openshift PR open, it's important to not have
regressions on their checks like lint, fmt, shellcheck, et al.  This
runs those on kni-installer PR's.

### CODE REVIEW

**Comment by metal3ci** [comment]
Build FAILURE, see build http://10.8.144.11:8080/job/dev-tools/795/

**Comment by stbenjam** [comment]
Needed to add a yum install for unzip.

**Comment by metal3ci** [comment]
Build FAILURE, see build http://10.8.144.11:8080/job/dev-tools/796/

**Comment by stbenjam** [comment]
Needs to be `sudo yum install`

**Comment by metal3ci** [comment]
Build SUCCESS, see build http://10.8.144.11:8080/job/dev-tools/797/

**Comment by stbenjam** [comment]
Tests are green

**Pull request merged**
