### PR TITLE
Retrieve installer sha from installer container if present

### PR DESCRIPTION
**Pull request by stbenjam**
If we're in OpenShift CI in an installer PR, then the installer is
built by rebasing on the target branch (i.e. master). The SHA that
`openshift-install version` reports doesn't exist on GitHub. It's only
in the environment that CI used to build the installer.

This gets the rhcos.json that's now in the baremetal-installer container. This avoids the CI problem, and avoids making any GitHub URL calls in 4.5 or later.

### CODE REVIEW

**Comment by stbenjam** [comment]
https://github.com/openshift/installer/pull/3330 is the alternative approach to save the rhcos.json

**Comment by metal3ci** [comment]
Build ABORTED, see build http://10.8.144.11:8080/job/dev-tools/1662/

**Comment by russellb** [comment]
current CI run is past these changes -- http://10.8.144.11:8080/job/dev-tools/1663/console

**Comment by metal3ci** [comment]
Build FAILURE, see build http://10.8.144.11:8080/job/dev-tools/1663/

**Pull request merged**
