### PR TITLE
Add PROVISIONING_NETWORK_PROFILE to config_example.sh

### PR DESCRIPTION
**Pull request by hardys**
This was missed in the original PR which added the variable

### CODE REVIEW

**Comment by stbenjam** [comment]
It could also be set to Unmanaged, if someone wants to go through the steps to setup a DHCP server themselves, but I suppose you excluded that since it's not really a built-in dev-scripts feature?

/lgtm
/approve

**Comment by hardys** [comment]
> I suppose you excluded that since it's not really a built-in dev-scripts feature?

Yeah exactly - we could add it in future, but it'd need either docs or automation of the external DHCP part, so I omitted that option for now to avoid confusion.

**Pull request merged**
