### PR TITLE
Support lease expiry option

### PR DESCRIPTION
**Pull request by cybertron**
This was added to metal3-dev-env in [0]. Expose the setting for
dev-scripts too.

With the current version of libvirt available, we are not able to run
virsh net-dhcp-leases when infinite leases are enabled. I've added
logic to skip that step when LEASE_EXPIRY=0. It just means we
can't retrieve clouds.yaml from the bootstrap.
    
0: https://github.com/metal3-io/metal3-dev-env/pull/599

### CODE REVIEW

**Comment by hardys** [comment]
Sorry this has been around for so long @cybertron - I'm just testing a metal3-dev-env patch, and noticed that we need this because the lease_expiry option is mandatory now in metal3-dev-env.

Could you update https://github.com/openshift-metal3/dev-scripts/blob/master/01_install_requirements.sh#L22 to pin to a recent/latest version which contains the lease-expiry change please?

I also needed the following galaxy role:

```
--- a/01_install_requirements.sh
+++ b/01_install_requirements.sh
@@ -43,7 +43,7 @@ sudo alternatives --set python /usr/bin/python3
 
 pushd ${METAL3_DEV_ENV_PATH}
 ansible-galaxy install -r vm-setup/requirements.yml
-ansible-galaxy collection install ansible.netcommon ansible.posix
+ansible-galaxy collection install ansible.netcommon ansible.posix community.general
```

**Comment by hardys** [comment]
Also it'd probably be good to add the new variable to `config_example.sh` - and do you think we should perhaps prefix the name e.g `DHCP_LEASE_EXPIRY` ?

**Comment by cybertron** [comment]
Okay, once I remembered that you need a newer libvirt for this to have any effect I was able to verify that infinite leases still work as expected after the changes we discussed above. I think this should be good to go once I push the new version.

**Pull request merged**
