### PR TITLE
Align install-config with kni-installer machinepools fix

### PR DESCRIPTION
**Pull request by hardys**
Testing with https://github.com/openshift-metal3/kni-installer/pull/128

### CODE REVIEW

**Comment by metal3ci** [comment]
Build SUCCESS, see build http://10.8.144.11:8080/job/dev-tools/800/

**Comment by hardys** [comment]
Ok removed the hack to test in CI, so this should be good to land when we've got the kni-installer PR landed and into a new image

**Comment by hardys** [comment]
Ok removed WIP so we can recheck/land this when the image is available

**Comment by stbenjam** [comment]
Can you update https://github.com/openshift-metal3/dev-scripts/blob/master/ocp_install_env.sh#L17 to point to 4.2.0-0.ci-2019-06-19-140700-kni.2

**Comment by hardys** [comment]
> Can you update https://github.com/openshift-metal3/dev-scripts/blob/master/ocp_install_env.sh#L17 to point to 4.2.0-0.ci-2019-06-19-140700-kni.2

Now done

**Comment by hardys** [comment]
> Can you update https://github.com/openshift-metal3/dev-scripts/blob/master/ocp_install_env.sh#L17 to point to 4.2.0-0.ci-2019-06-19-140700-kni.2

Now done

**Comment by metal3ci** [comment]
Build SUCCESS, see build http://10.8.144.11:8080/job/dev-tools/808/

**Pull request merged**
