### PR TITLE
use ROOT_DISK_NAME to set rootDeviceHints

### PR DESCRIPTION
**Pull request by dhellmann**
Always set the rootDeviceHints as a way to test and demonstrate the
feature.

### CODE REVIEW

**Comment by derekhiggins** [comment]
We should probably only set this if MASTER_HARDWARE_PROFILE isn't set as it would override anybody who is using profiles.

**Comment by dhellmann** [comment]
> We should probably only set this if MASTER_HARDWARE_PROFILE isn't set as it would override anybody who is using profiles.

I updated it to check both profile variables and to emit warnings if those are used instead of the device name variable.

**Pull request merged**
