### PR TITLE
4.2.0-0.nightly-2019-07-12-041904 rebase

### PR DESCRIPTION
**Pull request by hardys**
Testing https://github.com/openshift-metal3/kni-installer/pull/158

### CODE REVIEW

**Comment by metal3ci** [comment]
Build FAILURE, see build http://10.8.144.11:8080/job/dev-tools/886/

**Comment by metal3ci** [comment]
Build SUCCESS, see build http://10.8.144.11:8080/job/dev-tools/889/

**Comment by metal3ci** [comment]
Build SUCCESS, see build http://10.8.144.11:8080/job/dev-tools/891/

**Comment by metal3ci** [comment]
Build FAILURE, see build http://10.8.144.11:8080/job/dev-tools/893/

**Comment by metal3ci** [comment]
Build SUCCESS, see build http://10.8.144.11:8080/job/dev-tools/895/

**Comment by stbenjam** [comment]
Merged the rebase, and built http://registry.svc.ci.openshift.org/kni/release:4.2.0-0.nightly-2019-07-12-041904-kni.0 for us

**Comment by hardys** [comment]
> Merged the rebase, and built http://registry.svc.ci.openshift.org/kni/release:4.2.0-0.nightly-2019-07-12-041904-kni.0 for us

Thanks, patch updated to consume that build

**Comment by metal3ci** [comment]
Build SUCCESS, see build http://10.8.144.11:8080/job/dev-tools/897/

**Pull request merged**
