### PR TITLE
deploy a daemon set in cluster to autosign certs

### PR DESCRIPTION
**Pull request by karmab**
As a temporary solution, we provide an artifact which will autosign certs  after initial deployment

### CODE REVIEW

**Comment by russellb** [comment]
This duplicates the cron job that's running.  For dev-scripts, the cron job is probably good enough ...

**Comment by russellb** [comment]
Can you remove the cron job from script 11 in this PR?  I'll give it a try..

**Comment by karmab** [comment]
> Can you remove the cron job from script 11 in this PR? I'll give it a try..

done

**Comment by russellb** [comment]
This doesn't work for me.  The pod is in CrashLoopBackOff.

log:

```
# 2019-09-09T14:36:43Z Sync started
# 2019-09-09T14:36:43Z Sync 1192        /tmp/signer csr-stvbb Approved [...] system:node:master-2
/tmp/signer: line 25: openssl: command not found
error: Unable to parse certificate
# 2019-09-09T14:36:43Z Sync 458 /tmp/signer csr-wlp7s Approved [...] system:serviceaccount:openshift-machine-config-operator:node-bootstrapper
/tmp/signer: line 25: openssl: command not found
error: Unable to parse certificate
# 2019-09-09T14:36:43Z Sync 1186        /tmp/signer csr-6wr9l Approved [...] system:node:master-0

/tmp/signer: line 25: openssl: command not found
error: Unable to parse certificate
error: command "/tmp/signer" exited with status code 1
error: reached maximum error limit of 1, exiting
```

**Comment by metal3ci** [comment]
Build FAILURE, see build http://10.8.144.11:8080/job/dev-tools/1130/

**Pull request closed without merging**
