### PR TITLE
Fix IPv6 URL bracketing for image polling

### PR DESCRIPTION
**Pull request by stbenjam**

### CODE REVIEW

**Comment by russellb** [comment]
lgtm

**Comment by metal3ci** [comment]
Build FAILURE, see build http://10.8.144.11:8080/job/dev-tools/1559/

**Comment by metal3ci** [comment]
Build FAILURE, see build http://10.8.144.11:8080/job/dev-tools/1566/

**Comment by metal3ci** [comment]
Build SUCCESS, see build http://10.8.144.11:8080/job/dev-tools/1578/

**Pull request merged**
