### PR TITLE
using slash delimiters in sysctl for handling vlan NICs

### PR DESCRIPTION
**Pull request by osherdp**
Happened to me on a scalelab machine.
Figured out we can handle it in this way.

/hold

### CODE REVIEW

**Comment by hardys** [comment]
Tested some sysctl commands locally and seems to work OK, I've not got vlans setup to test with the nic.vlan naming though.

/approve

**Comment by osherdp** [comment]
/unhold
Yes, it worked on my setup that has vlans

**Review by elfosardo — APPROVED** [review]

**Pull request merged**
