### PR TITLE
NO-ISSUE: configure install-config.yaml proxy when required

### PR DESCRIPTION
**Pull request by andfasano**
This patch fixes the agent scenarios when a proxy is configured via the `INSTALLER_PROXY` config var. 
Without this patch, all the (connected) scenario - such as the following - are broken:

```
export AGENT_E2E_TEST_SCENARIO=COMPACT_IPV4
export INSTALLER_PROXY=true
```

### CODE REVIEW

**Comment by andfasano** [comment]
Note: useful to test https://github.com/openshift/oc/pull/1857

**Review by pawanpinjarkar — COMMENTED** [review]
/lgtm

**Pull request merged**
